### ISSUE TITLE
It seems that it's not friendly for Options in Quote functions.

### ISSUE THREAD

**Issue by haku0416** [Sinotrade/Shioaji#10]
The APIs are friendly for Stocks and Futures, but not for Options.
I use the APIs to do Option quoting and encounter the error response "Max Num Subscriptions Exceeded". 
I think that "Is there a method to subscribe the big title like "TXO201904" or "TXO201904W4" which tag does not include the details (like TXO201904W4**C10100**,TXO201904W4**P10100**,TXO201904W4**C10200**,TXO201904W4**P10200**)?"
Thanks.

**Comment by Yvictor** [comment]
@haku0416 Currently we just for pre-alpha testing, all the account can only subscribe 5 contract simultaneously. So subscribe Like TXO201904W4 all strike contract will directly over the limit, we will provide better interface for options when the subscribe limit depend on difference user account.

**Comment by haku0416** [comment]
Thanks for your reply.
