### ISSUE TITLE
小台期貨2021年五月合約 5/12  5/13  5/14  ticks資料無法下載

### ISSUE THREAD

**Issue by roger0915** [Sinotrade/Shioaji#100]
ticks = api.ticks(api.Contracts.Futures["MXF"]['MXF202105'],"2021-05-14")
df = pd.DataFrame({**ticks})
df.ts = pd.to_datetime(df.ts)
df.tail()
df.to_csv('2021-05-14小台.csv', encoding = 'utf_8_sig')

出現以下訊息  煩請告知原因為何  感恩
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-9-c058c4d59d96> in <module>
      9 
     10 #讀取tick data
---> 11 ticks = api.ticks(api.Contracts.Futures["MXF"]['MXF202105'],"2021-05-14")
     12 df = pd.DataFrame({**ticks})
     13 df.ts = pd.to_datetime(df.ts)

~\Anaconda3\lib\site-packages\shioaji\shioaji.py in ticks(self, contract, date, timeout, cb)
    553             date (str): "2020-02-02"
    554         """
--> 555         ticks = self._solace.ticks(contract, date, timeout, cb)
    556         return ticks
    557 

shioaji\backend\solace\api.pyx in shioaji.backend.solace.api.SolaceAPI.ticks()

shioaji\backend\solace\api.pyx in shioaji.backend.solace.api.SolaceAPI._ticks_cb()

~\Anaconda3\lib\site-packages\shioaji\utils.py in raise_resp_error(status_code, resp)
     47         raise SystemMaintenance(status_code, detail)
     48     else:
---> 49         raise Exception(resp)

Exception: {}

**Comment by ypochien** [comment]
---> 49 raise Exception(resp)

Exception: {}

出現以上訊息，皆是因為數量太大，導致預設5秒的Timeout時間不夠，在ticks的timeout參數設定大一點(timeout=30000 為 30秒)
