### ISSUE TITLE
Please supply macOS use shioaji

### ISSUE THREAD

**Issue by GeorgioWan** [Sinotrade/Shioaji#105]
爬文發現到目前好像還是沒有直接支援 macOS 使用 shioaji 進行開發，
近來在開發階段使用 macOS 的用戶應該是提升不少，還請貴司技術團隊考慮支援一下，感謝 🙇

**Comment by ypochien** [comment]
macOS可以直接使用 只是無法操作憑證(下單需要)
目前建議,如果真的需要在OSX 上下單，只能先透過docker
