### ISSUE TITLE
ImportError: DLL load failed while importing solclient: 動態連結程式庫 (DLL) 初始化例行程序失敗。

### ISSUE THREAD

**Issue by Suneasting** [Sinotrade/Shioaji#106]
您好：
遇到了這個問題。請幫忙!
window 10 64 bits
python 3.8.10
pipenv 的virtual environment

shioaji==0.3.2.dev8
  - importlib-metadata [required: ==1.6.0, installed: 1.6.0]
    - zipp [required: >=0.5, installed: 3.4.1]
  - loguru [required: ==0.4.1, installed: 0.4.1]
    - colorama [required: >=0.3.4, installed: 0.4.4]
    - win32-setctime [required: >=1.0.0, installed: 1.0.3]
  - pydantic [required: ==1.0.0, installed: 1.0]
  - pysolace [required: ==0.9.10, installed: 0.9.10]
    - loguru [required: Any, installed: 0.4.1]
      - colorama [required: >=0.3.4, installed: 0.4.4]
      - win32-setctime [required: >=1.0.0, installed: 1.0.3]
    - msgpack [required: Any, installed: 1.0.2]
    - orjson [required: ==3.3.1, installed: 3.3.1]
    - sentry-sdk [required: Any, installed: 0.14.1]
      - certifi [required: Any, installed: 2021.5.30]
      - urllib3 [required: >=1.10.0, installed: 1.25.11]
  - requests [required: ==2.22.0, installed: 2.22.0]
    - certifi [required: >=2017.4.17, installed: 2021.5.30]
    - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
    - idna [required: >=2.5,<2.9, installed: 2.8]
    - urllib3 [required: >=1.21.1,<1.26,!=1.25.1,!=1.25.0, installed: 1.25.11]
  - sentry-sdk [required: ==0.14.1, installed: 0.14.1]
    - certifi [required: Any, installed: 2021.5.30]
    - urllib3 [required: >=1.10.0, installed: 1.25.11]
  - xxhash [required: ==2.0.0, installed: 2.0.0]
謝謝!
![動態連結程式庫(DLL) 初始化例行程序失敗](https://user-images.githubusercontent.com/48337399/121092581-5b397b80-c81e-11eb-8854-680a310aaadf.png)

**Comment by twken** [comment]
python 3.8.10 
就是要用 3.8以下的版本
