### ISSUE TITLE
關於選擇權組合單 保證金優化

### ISSUE THREAD

**Issue by amosfan** [Sinotrade/Shioaji#108]
請問 永豐 API 是不是沒有提供關於選擇權組合單 保證金優化 的下單方式？
(永豐 API 官網似乎沒有相關介紹。)

所以 買權多頭價差，買權空頭價差，賣權多頭價差，賣權空頭價差
這四種組合單是不是都沒有辦法做保證金優化？

**Comment by ypochien** [comment]
目前沒有...請見諒...

**Comment by hihihlo** [comment]
我看到官方已有提供 : https://sinotrade.github.io/zh_TW/tutor/order/Combo/
如果我誤會了, 請告訴我
