### ISSUE TITLE
無法安裝最新版本

### ISSUE THREAD

**Issue by tom888888** [Sinotrade/Shioaji#109]
ERROR: Could not find a version that satisfies the requirement shioaji==0.3.2.dev9 (from versions: 0.3.0.dev0, 0.3.0.dev2, 0.3.0.dev3, 0.3.0.dev4, 0.3.0.dev5, 0.3.0.dev7, 0.3.0.dev8, 0.3.0.dev9, 0.3.1.dev1, 0.3.1.dev2, 0.3.1.dev4, 0.3.1.dev6, 0.3.1.dev8, 0.3.2.dev1, 0.3.2.dev2, 0.3.2.dev3, 0.3.2.dev4)
ERROR: No matching distribution found for shioaji==0.3.2.dev9

python version : Python 3.8.10
pip version : pip 21.1.3

**Comment by ypochien** [comment]
從你的錯誤訊息來看 你的pip環境就吃不到 0.3.2.dev4之後的版本...這部分幫我確認一下...
你環境是Windows還是?

**Comment by Hsinfu** [comment]
hihi @ypochien 看起來是build fail嗎？從0.3.2.dev5 開始都 fail
https://github.com/Sinotrade/Shioaji/actions/runs/769065372
