### ISSUE TITLE
和finmind 套件衝突

### ISSUE THREAD

**Issue by aga4gavin** [Sinotrade/Shioaji#110]
因為shioaji不支援日K資料，所以同時使用finmind，但兩個套件的dependence互相衝突，看來shioaji只要特定版本的套件，請問可以放寬，或是有甚麼建議嗎？

finmind 1.4.6 requires loguru~=0.5.3
finmind 1.4.6 requires pydantic~=1.6.1
finmind 1.4.6 requires requests~=2.23.0

shioaji 0.3.2.dev9 requires loguru==0.4.1
shioaji 0.3.2.dev9 requires pydantic==1.0.0
shioaji 0.3.2.dev9 requires requests==2.22.0

**Comment by ypochien** [comment]
這個是已知的問題...有那麼一天會修正Orz
