### ISSUE TITLE
無法安裝

### ISSUE THREAD

**Issue by inziihand** [Sinotrade/Shioaji#115]
Python 3.9.4
pip 21.1.3

pip install shioaji
ERROR: Could not find a version that satisfies the requirement shioaji (from versions: none)
ERROR: No matching distribution found for shioaji

**Comment by YutangShi** [comment]
i have same issue on macOS and ubuntu 20.04

**Comment by josephorng** [comment]
Me too

**Comment by chuangtc** [comment]
It seems it works only in Ubuntu 18.04 Python 3.7 for Shioaji v0.3.2.dev9
https://chuangtc.com/projects/sinopac_trade_python_api_shioaji.php
