### ISSUE TITLE
get error msg "內部驗證失敗, 這個憑證鏈捨棄不使用, 無法用來驗憑證鏈" when running in docker of sinotrade/shioaji

### ISSUE THREAD

**Issue by dapast1289** [Sinotrade/Shioaji#116]
我在mac上開發，將寫好的程式和憑證放入永豐提供的docker裏面去起動，但ca.log會出現

2021/07/14 08:13:52.177 (PID=163) ERROR 	|	|--- 驗章失敗, 原因 = ok
2021/07/14 08:13:52.181 (PID=163) ERROR 內部驗證失敗, 這個憑證鏈捨棄不使用, 無法用來驗憑證鏈

這兩條訊息
看起來憑證是有讀取密碼也正確，但掛單的動作沒有一次是成功的．

**Comment by lingchingteng** [comment]
借這裡問一下，ubuntu 好像也是這個 log 。

所以不是 windows 的平台，可以抓資料不能下單是嗎？

**Comment by dapast1289** [comment]
後來發現他是有生效，只是是在下一個交易日(開盤前)才會出現
