### ISSUE TITLE
API 文件修改 (action) 與命名

### ISSUE THREAD

**Issue by OppOops** [Sinotrade/Shioaji#12]
1.  `api.OrderProps.Future.action.Buy` 以及 `api.OrderProps.Future.action.Sell` 似乎分別改成了 `"Buy"` 與 `"Sell"`，而不是原本字串 `"B"` 或 `"S"`。這個和 doc string 描述的不一致。在 limit_order 舉例的部分：

```python
    sample_limit_order = api.LimitOrder('B', 9700, 5)
    sample_limit_order
```
```
    LimitOrder(action='B', order_type='ROD', price=9700, quantity=5)
```
現在也不能使用 `"B"` 或 `"S"` 作為 `api.LimitOrder` 的參數了。
***
2. `api.OrderProps.Future` 這個命名指的應該是期貨？ 所以應該是 `api.OrderProps.Futures` ？希望能夠確認一下，謝謝。

**Comment by ypochien** [comment]
感謝您的寶貴建議，目前產品持續開發中，會討論這部分的設計。
