### ISSUE TITLE
選擇權可下複式單嗎？

### ISSUE THREAD

**Issue by sromeoi** [Sinotrade/Shioaji#121]
看說明文檔只看到單式order方式，有可以下複式單（組合單）方式嗎？
謝謝

**Comment by ypochien** [comment]
目前複式單 正在 開發中

**Comment by hihihlo** [comment]
我看到官方已有提供 : https://sinotrade.github.io/zh_TW/tutor/order/Combo/
如果我誤會了, 請告訴我
