### ISSUE TITLE
api.kbars資料問題

### ISSUE THREAD

**Issue by endercoding** [Sinotrade/Shioaji#122]
1. api.kbars 找個股 4766,4743，發現數值為 0 的資料，似乎是和暫停交易有關係?
2. api.kbars(api.Contracts.Indexs.TSE.TSE001) 2021-05-01 ~ 2021-05-17 的資料下載不到，但 api.ticks似乎是正常的
3. api.kbars 資料起始從 2018 開始，個股、指數，會出現重複 index

**Comment by ypochien** [comment]
感謝反饋，我們會再找時間修復
