### ISSUE TITLE
虛擬帳戶 v1.0.0

### ISSUE THREAD

**Issue by jimmylin0979** [Sinotrade/Shioaji#128]
Shioaji 在 v1.0.0 版本後啟用 Token 作為登入依據，想請問還有辦法使用虛擬帳戶登入嗎？

如下圖，Shioaji 在 <1.0.0 版本時，可以用虛擬帳戶登入
```python
import shioaji as sj
api = sj.Shioaji(simulation=False)
api.login(
    person_id="PAPIUSER02",
    passwd="2222",
    contracts_cb=lambda security_type: print(f"{repr(security_type)} fetch done.")
)
```

但我目前無法在 document 內找到 1.0.0 版本虛擬帳戶登入的方式，請問應該如何處理？
感謝！

**Comment by lyenliang** [comment]
從[這份文件](https://sinotrade.github.io/tutor/simulation/)來看，似乎只要設定 `api = sj.Shioaji(simulation=True)` 就能使用虛擬帳戶。
