### ISSUE TITLE
api.list_positions 不會即時更新庫存的數量

### ISSUE THREAD

**Issue by Perry89-Huang** [Sinotrade/Shioaji#129]
我的程式 收到完成交易的 FDeal資訊之後，我用 api.list_positions 去檢查我期貨的庫存，發現 我的庫存並沒有更新到這次的交易，我大約要等 1～2分鐘之後，庫存的資訊才會被更新。請問如何解決這個問題，讓庫存的資訊能即時的更新?

**Comment by luckchiao** [comment]
已修復上線
