### ISSUE TITLE
升級到 1.0 之後，就沒有收到 Futures Order的 OrderState.FuturesDeal資訊

### ISSUE THREAD

**Issue by Perry89-Huang** [Sinotrade/Shioaji#130]
我再升級到 1.0之前,當 Futures Order 成交之後，我會收到 OrderState.FDeal 的 callback訊息。
但我升級到 1.0之後，就收不到 OrderState.FuturesDeal的資訊了。
請問我是否還需要做甚麼動作 才能在 1.0 收到 Futures Order的 OrderState.FuturesDeal資訊嗎?

**Comment by ypochien** [comment]
主動回報這部分接收沒有變，1.0之後改變的只是收到的內容會從 您說的  OrderState.FDeal 變成  OrderState.FuturesDeal

如果還是有您說的現象，請直接在 Telegram群組 找我協助確認 
[Python API - Shioaji 客戶服務群組](https://t.me/+MLbqzvPpfWM5M2Y1)
