### ISSUE TITLE
Shioaji 在osx ARM64 c# net6.0 錯誤  Could not load file or assembly 'SolaceSystems.Solclient.Messaging'

### ISSUE THREAD

**Issue by superdavid0816** [Sinotrade/Shioaji#131]
您好，請問，我使用osx, cpu:arm64,  visula studio c# net6.0，使用nuget安裝shioaji 0.0.9-dev1，依照範例
using System;
using Sinopac.Shioaji;

Shioaji _api = new Shioaji();
var _accounts = _api.Login("YOUR_PERSON_ID", "YOUR_PASSWORD");  
在最後一行執行後出現錯誤

"Could not load file or assembly 'SolaceSystems.Solclient.Messaging, Version=10.19.0.0, Culture=neutral, PublicKeyToken=e191a36e57c23464'. The system cannot find the file specified.\n"

在NuGet底下的shioaji底下可以看見相依套件SolaceSystems.Solclient.Messaging有自動安裝

請問該如何使用？

謝謝

**Comment by luckchiao** [comment]
是x64，不是arm64
