### ISSUE TITLE
Shioaji 在 osx ARM64 python version 3.8.16, 3.9.16, 3.10.10, 3.11.1 無法安裝

### ISSUE THREAD

**Issue by superdavid0816** [Sinotrade/Shioaji#132]
您好

我在 osx ARM64 裡面要安裝shioaji
依照說明操作安裝，出現錯誤

pip install shioaji

ERROR: Could not find a version that satisfies the requirement shioaji (from versions: none)
ERROR: No matching distribution found for shioaji

使用pipenv切換以下版本
3.8.16, 3.9.16, 3.10.10, 3.11.1
仍出現相同錯誤無法安裝

請問應該如何操作

謝謝

**Comment by HughesWang** [comment]
我 osx arm64 一樣也是沒辦法安裝

python 3.7 只支援 x86

**Comment by r888800009** [comment]
M1 上面似乎可以用 conda 去運行
```bash
conda create --name shioaji
conda activate shioaji
conda config --env --set subdir osx-64
conda install python=3.7
python3 -m pip install shioaji
```

**Comment by ypochien** [comment]
目前只支援X86系列的CPU，對於MAC M1、M2的部分，需透過 Apple Rosetta 來運行 X86的Python即可
可以參閱 https://towardsdatascience.com/how-to-use-manage-multiple-python-versions-on-an-apple-silicon-m1-mac-d69ee6ed0250
