### ISSUE TITLE
請協助解決以下的exception, 會造成系統突然的結束

### ISSUE THREAD

**Issue by sunnylin13** [Sinotrade/Shioaji#133]
ERROR    | pysolace:event_callback_wrap:118 - An error has been caught in function 'event_callback_wrap', process 'MainProcess' (4392), thread 'Dummy-63' (9092):
Traceback (most recent call last):

> File "C:\.venv\finfun-ieOOA8bn-py3.11\Lib\site-packages\pysolace\__init__.py", line 119, in event_callback_wrap
    self.event_callback(resp_code, event, info, event_str)
    │    │              │          │      │     └ 'Session up'
    │    │              │          │      └ "host '203.66.91.161:80', hostname '203.66.91.161:80' IP 203.66.91.161:80 (host 1 of 1) (host connection attempt 1 of 1) (tot...
    │    │              │          └ 0
    │    │              └ 0
    │    └ <bound method SolClient.onreply_callback_wrap of <pysolace.SolClient object at 0x00000243BE1D8190>>
    └ <pysolace.SolClient object at 0x00000243BE1D8190>

**TypeError: SolClient.onreply_callback_wrap() takes 4 positional arguments but 5 were given**

**Comment by ypochien** [comment]
請更新至 [v1.1.2](https://pypi.org/project/shioaji/1.1.2/)，已解決此現象，造成不便請見諒
