### ISSUE TITLE
1. 無法cancel order, 2. update_status不靈光, 3. updata_status(trade) Error

### ISSUE THREAD

**Issue by twironman** [Sinotrade/Shioaji#140]
![image](https://user-images.githubusercontent.com/130856195/232237342-66c8001e-4c9b-4244-bfb3-c15a07a04fed.png)
1. 用API cancel order時出現error要求update_status 但是明明已經update_status+list_trade 後面不管update_status幾次都一樣無法cancel 測試環境: 周末丟的pendingsubmitted單 無法用API cancel 幾個月前這動作在同樣情況應該可以正常執行

2. a. 用e-leader手動丟的預約單 在API裡用update_status無法讀取到 此時e-leader看到的單子數目和API看到的單子數目不match 不管等多久update_satus幾次都不match (已經吃CA 可以正常丟單 但讀到的單子不match 只讀的到API丟的單子)
   b. 用e-leader砍完所有單後 用update_status+list_trade api還看的到早就被砍掉的單子 等多久後都看的到顯示狀態並沒有變成cancelled

3. 文檔說可以api.update_status(trade)
但實際上實驗會出現error: 他會說找不到signed (應該是找錯data hierarchy)

shioaji 版本: 1.1.2

**Comment by ypochien** [comment]
無法複現你說的現象，請到telegram 找我，讓我協助你確認

但你說的第三點，請注意update_status有幾個參數，你需要update_status(trade=你的trade物件) 沒帶參數名稱第一個會是account
