### ISSUE TITLE
請問docker的jovyan帳號的密碼

### ISSUE THREAD

**Issue by ben30510** [Sinotrade/Shioaji#169]
想使用sudo權限去安裝其他package 有提供密碼嗎?
或是我要自己拉一個新的linux docker 自己裝

**Comment by Yvictor** [comment]
https://github.com/Sinotrade/Shioaji/blob/master/Dockerfile-jupyter

Jupyter 的 Image 裡面的 base image 是用這個 jupyter/datascience-notebook:python-3.8.5

他是在 build 的時候是用 root 安裝 
可以參考他的 Dockerfile 再看一下我們的安裝，基本上沒做太多事，自行 build 就可以了

**Comment by ben30510** [comment]
@ypochien 您好 另外想請問有委託狀態的parser嗎? 他回傳的值有點難讀 或是只能自己寫parser?
感謝您的回覆
