### ISSUE TITLE
股票即時庫存資訊

### ISSUE THREAD

**Issue by phl1510** [Sinotrade/Shioaji#17]
請問有辦法取得Account的即時股票庫存資訊嗎？

**Comment by Yvictor** [comment]
@phl1510 
請更新一下
目前已經有提供證券庫損益相關資訊了
```
get_stock_account_funds
get_stock_account_unreal_profitloss
get_stock_account_real_profitloss
```
目前是暫定的，我們希望聽到一些用戶反饋後能做一些比較好用的修正
使用方式跟期貨的暫時一樣
.data()可以拿到list[dict]格式的資料
可以直接丟進pandas Dataframe
可以參考期貨的openposition那邊的範例

**Comment by phl1510** [comment]
It works, thanks a lot
