### ISSUE TITLE
cannot install package on macOS 10.14.6

### ISSUE THREAD

**Issue by Ed-Yang** [Sinotrade/Shioaji#18]
Try to install on macOS, but failed.  (On Debian Linux, it work well)

$ python --version
Python 3.7.1

$ pip3 install  shioaji
Collecting shioaji
  ERROR: Could not find a version that satisfies the requirement shioaji (from versions: none)
ERROR: No matching distribution found for shioaji

**Comment by ypochien** [comment]
I suggest you use Linux and Windows first.
because some reason, we don't release the macOS version.
In the feature to come , we will release it.

**Comment by Yvictor** [comment]
[0.3.0.dev0](https://github.com/Sinotrade/Shioaji/releases/tag/0.3.0.dev0)
