### ISSUE TITLE
請問可以查詢個股的歷史股價嗎？

### ISSUE THREAD

**Issue by weini2** [Sinotrade/Shioaji#21]
請問可以查詢個股的歷史股價嗎？

有無範例可以提供？

**Comment by ypochien** [comment]
目前行情只有提供即時的報價揭示
**歷史**資料的部分，開發中

**Comment by KN16H7** [comment]
看起來 api.ticks(api.Contracts.Stocks(StockID, Date) 已經有了, 有預計要支援 api.Contracts.Futures 嗎?: )

**Comment by ypochien** [comment]
![image](https://user-images.githubusercontent.com/625016/80617276-7b700600-8a74-11ea-97b3-8891d2f84a6d.png)
