### ISSUE TITLE
api.active_ca()問題

### ISSUE THREAD

**Issue by luanya01** [Sinotrade/Shioaji#24]
api.active_ca(r'D:\Program Files\eleader\Cert\SinoPac.pfx','xxxxxx','myID') 
只要密碼正確，ID隨便打都會顯示
`Ca Initial Done.
0`
應該是沒確認到憑證內id?

**Comment by ypochien** [comment]
這邊傳入的id的確無關憑證。
憑證本來就是專屬於個人的ID，這部分的是我們設計界面上的疏失。
