### ISSUE TITLE
trade.status.status回传清单

### ISSUE THREAD

**Issue by DavidWang293** [Sinotrade/Shioaji#27]
请问， trade = api.place_order(self.TradedTarget, Buy_order)
trade.status.status 回传讯息只有“PendingSubmit” ，“Submitted”？
已成交会回传什么？ 已撮合未成交会回传什么？

可否提供回传讯息的明细

**Comment by ypochien** [comment]
Status of Trade
狀態說明如下:
PendingSubmit: 傳送中
PreSubmitted: 預約單
Submitted: 傳送成功
Failed: 失敗
Cancelled: 已刪除
Filled: 完全成交
Filling: 部分成交

完整說明文件可參考
https://sinotrade.github.io/tutor/order/Stock_Trade_for_Trade/
