### ISSUE TITLE
Callback 回傳 Tick 資料有問題

### ISSUE THREAD

**Issue by KN16H7** [Sinotrade/Shioaji#28]
爬資料幾個月來第一次發生, len(TickType|DiffType)=20, len(其他)=19, 會導致 dict 不能直接給 pd 丟 dataframe (其實更在意的是資料品質是否有問題)

--- cut ---
L/TFE/MXFC0 {"Amount": [11795.0, 23584.0, 23584.0, 23584.0, 23584.0, 23584.0, 23584.0, 23584.0, 23584.0, 23584.0, 23584.0, 23584.0, 23584.0, 23584.0, 23584.0, 23584.0, 23584.0, 23584.0, 23584.0], "AmountSum": [1674890.0, 1698474.0, 1722058.0, 1745642.0, 1769226.0, 1792810.0, 1816394.0, 1839978.0, 1863562.0, 1887146.0, 1910730.0, 1934314.0, 1957898.0, 1981482.0, 2005066.0, 2028650.0, 2052234.0, 2075818.0, 2099402.0], "AvgPrice": [11795.0, 11794.958333333334, 11794.917808219177, 11794.878378378378, 11794.84, 11794.802631578947, 11794.766233766233, 11794.73076923077, 11794.696202531646, 11794.6625, 11794.62962962963, 11794.59756097561, 11794.56626506024, 11794.535714285714, 11794.505882352942, 11794.476744186046, 11794.448275862069, 11794.420454545454, 11794.393258426966], "Close": [11795.0, 11792.0, 11792.0, 11792.0, 11792.0, 11792.0, 11792.0, 11792.0, 11792.0, 11792.0, 11792.0, 11792.0, 11792.0, 11792.0, 11792.0, 11792.0, 11792.0, 11792.0, 11792.0], "Code": "MXFC0", "Date": "2020/01/30", "DiffPrice": [-300.0, -303.0, -303.0, -303.0, -303.0, -303.0, -303.0, -303.0, -303.0, -303.0, -303.0, -303.0, -303.0, -303.0, -303.0, -303.0, -303.0, -303.0, -303.0], "DiffRate": [-2.4803637866887143, -2.5051674245556015, -2.5051674245556015, -2.5051674245556015, -2.5051674245556015, -2.5051674245556015, -2.5051674245556015, -2.5051674245556015, -2.5051674245556015, -2.5051674245556015, -2.5051674245556015, -2.5051674245556015, -2.5051674245556015, -2.5051674245556015, -2.5051674245556015, -2.5051674245556015, -2.5051674245556015, -2.5051674245556015, -2.5051674245556015], "DiffType": [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4], "High": [11795.0, 11795.0, 11795.0, 11795.0, 11795.0, 11795.0, 11795.0, 11795.0, 11795.0, 11795.0, 11795.0, 11795.0, 11795.0, 11795.0, 11795.0, 11795.0, 11795.0, 11795.0, 11795.0], "Low": [11764.0, 11764.0, 11764.0, 11764.0, 11764.0, 11764.0, 11764.0, 11764.0, 11764.0, 11764.0, 11764.0, 11764.0, 11764.0, 11764.0, 11764.0, 11764.0, 11764.0, 11764.0, 11764.0], "Open": 11795.0, "TargetKindPrice": 12118.71, "TickType": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "Time": "08:45:00.105000", "TradeAskVolSum": 39, "TradeBidVolSum": 149, "VolSum": [142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178], "Volume": [1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]}
--- cut ---

**Comment by ypochien** [comment]
請見諒，日前報價的bug已有進行修正。
請您在多多觀察指教
