### ISSUE TITLE
'Shioaji' object has no attribute 'fut_account'

### ISSUE THREAD

**Issue by white05** [Sinotrade/Shioaji#29]
在docker環境下的 0.0.6.dev6 可以運行
但你們最新release的版本 0.1.1.dev0 

這個是event_callback訊息

Response Code: 0 | Event Code: 0 | Info: host '203.66.91.161:80', IP 203.66.91.161:80 (host 1 of 1) (host connection attempt 1 of 1) (total connection attempt 1 of 1) | Event: Session 
up

就會出現以下錯誤

`Unexpected error: (<class 'AttributeError'>, AttributeError("'Shioaji' object has no attribute 'fut_account'",), <traceback object at 0x7fccc408f308>)`

**Comment by Yvictor** [comment]
@white05  抱歉文件還沒更新
fut_account  -> futopt_account

**Comment by white05** [comment]
是不是裡面有很多參數都改了，因為 api.Contracts.Futures 裡面好像也是空的 @@

**Comment by Yvictor** [comment]
0.1.0以後是更改架構但是大部分跟0.0.6.dev8是一樣的
介面以增加為原則不異動動原本的function異動目標都向下相容
api.Contracts部分變成NonBlocking在背景做了
原本登入很慢是因為還需要下載商品檔下載完登入function才會完成
目前登入會下載商品檔但不會Blocking直到下載檔案回來了才會寫入Contracts
所以你過一下就會看到Contracts裡面有東西了
在登入function裡面有留一個callback可以在下載完執行你要執行的東西
預設callback是寫log通知完成

**Comment by white05** [comment]
了解，我等等來試試那個callback

**Comment by KN16H7** [comment]
0.1.0 api.quote.subscribe 參數跟 0.0.6 對不上, 如果向下相容的話, 0.0.6 的 code 搬到 0.1 應該可以直接用 orz...

>>> api.quote.subscribe(api.Contracts.Indexs.TSE['TSE001'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "shioaji/backend/solace/api.pyx", line 588, in shioaji.backend.solace.api.SolaceAPI.subscribe
TypeError: subscribe() takes exactly 3 positional arguments (2 given)

>>> api.quote.subscribe(api.Contracts.Futures['MXFC0'], quote_type='tick')
>>> 2020-02-29 01:39:51.541 | ERROR    | pysolace:event_callback_wrap:106 - An error has been caught in function 'event_callback_wrap', process 'MainProcess' (1679), thread 'Dummy-1' (140374750136064):
Traceback (most recent call last):

  File "/usr/local/lib64/python3.6/site-packages/pysolace/__init__.py", line 106, in event_callback_wrap
    self.event_callback(resp_code, event, info, event_str)
    │    │              │          │      │     └ 'Subscribe or Unsubscribe ok'
    │    │              │          │      └ 'L/*/MXFC0'
    │    │              │          └ 16
    │    │              └ 200
    │    └ <bound method SolaceAPI.on_event_wrap of <shioaji.backend.solace.api.SolaceAPI object at 0x7fab8f72def0>>
    └ <pysolace.SolClient object at 0x7fab8c485dd8>

> File "shioaji/backend/solace/api.pyx", line 606, in shioaji.backend.solace.api.SolaceAPI.on_event_wrap
  File "shioaji/backend/utils.pyx", line 31, in shioaji.backend.utils.on_event.wrapper_event_callback
  File "<stdin>", line 6, in event_callback

NameError: name 'CurrentTradingFileNameStr' is not defined

**Comment by ypochien** [comment]
> 0.1.0 api.quote.subscribe 參數跟 0.0.6 對不上, 如果向下相容的話, 0.0.6 的 code 搬到 0.1 應該可以直接用 orz...
> 
> > > > api.quote.subscribe(api.Contracts.Indexs.TSE['TSE001'])
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "shioaji/backend/solace/api.pyx", line 588, in shioaji.backend.solace.api.SolaceAPI.subscribe
> > > > TypeError: subscribe() takes exactly 3 positional arguments (2 given)
> 
> > > > api.quote.subscribe(api.Contracts.Futures['MXFC0'], quote_type='tick')
> > > > 2020-02-29 01:39:51.541 | ERROR    | pysolace:event_callback_wrap:106 - An error has been caught in function 'event_callback_wrap', process 'MainProcess' (1679), thread 'Dummy-1' (140374750136064):
> > > > Traceback (most recent call last):
> 
> File "/usr/local/lib64/python3.6/site-packages/pysolace/**init**.py", line 106, in event_callback_wrap
> self.event_callback(resp_code, event, info, event_str)
> │ │ │ │ │ └ 'Subscribe or Unsubscribe ok'
> │ │ │ │ └ 'L/*/MXFC0'
> │ │ │ └ 16
> │ │ └ 200
> │ └ <bound method SolaceAPI.on_event_wrap of <shioaji.backend.solace.api.SolaceAPI object at 0x7fab8f72def0>>
> └ <pysolace.SolClient object at 0x7fab8c485dd8>
> 
> > File "shioaji/backend/solace/api.pyx", line 606, in shioaji.backend.solace.api.SolaceAPI.on_event_wrap
> > File "shioaji/backend/utils.pyx", line 31, in shioaji.backend.utils.on_event.wrapper_event_callback
> > File "", line 6, in event_callback
> 
> NameError: name 'CurrentTradingFileNameStr' is not defined

這個版本我們不小心把訂閱的預設值拿掉了，已經補回。
這部分文件也已更新
https://sinotrade.github.io/tutor/market_data/streaming/#tick
