### ISSUE TITLE
Win10-64bit , python3.6.5,  pip install shioaji error

### ISSUE THREAD

**Issue by a9202507** [Sinotrade/Shioaji#30]
Win10-64bit, python3.6.5, 
c:> pip install shioaji
**ERROR: Could not find a version that satisfies the requirement shioaji (from versions: none)
ERROR: No matching distribution found for shioaji**

用pip安裝別的套件正常。

**Comment by ypochien** [comment]
這部分，再請確認一下。
如果之前有裝過，或許會因為套件相依性的關係
執行 pip install shioaji -U 更新看看
![image](https://user-images.githubusercontent.com/625016/77542861-ce88f300-6ee1-11ea-9e1b-346c3116a029.png)

**Comment by Yvictor** [comment]
you should use python 64 bit on windows
