### ISSUE TITLE
error install

### ISSUE THREAD

**Issue by tsaohucn** [Sinotrade/Shioaji#31]
`pip3 install shioaji`

ERROR: Could not find a version that satisfies the requirement shioaji (from versions: none)
ERROR: No matching distribution found for shioaji

這套件還有在維護嗎？

**Comment by KN16H7** [comment]
on python 3.8?

**Comment by q10242** [comment]
same problem here, cannot install

**Comment by KN16H7** [comment]
強烈建議暫時先不要玩他們最新版, 文件也還沒跟上, 當然也不要奢望該司的師程工們有力氣回覆, 我搞了半天又用回 python 3.6.8 + 0.0.6x, 不求新只求穩定, 畢竟是用來跟錢打交道的, 真出了問題也不知道要跟誰哭~

**Comment by ypochien** [comment]
讓您們的體驗不佳是我們該改善的...

我們這幾天review 一下issue...

或者願意私下協助我們改善產品也可以私訊跟我聯系。我mail ypochien@gmail.com

**Comment by ypochien** [comment]
我們目前還沒有釋出3.8版本

**Comment by a9202507** [comment]
我也是一直裝不起來，目前我用docker 來試，就可以專注在api 上面了。

**Comment by ypochien** [comment]
@a9202507 請問您遇到的issue 有沒有資訊可以提供給我進行排除~

**Comment by a9202507** [comment]
因為我的python 一直無法pip install shioaji. 所以我跳過. 直接用你們提供的Docker image. 安裝出預裝shioaji的python.

**Comment by a9202507** [comment]
我用raspberry pi4 ，python 3.7 一樣也是不能裝.

**Comment by KN16H7** [comment]
先回樓上的問題, 他們應該還只支援 win/linux on x86/x64, 技術問題猜想應該是 TWCA 吧? 不過建議團隊能在 README.md 說明清楚會更好 (包括不支援 mac 以及 arm-based), 我一開始也踩過這種雷.

話說升級到 0.2.0.dev1 了, 觀察了 24hr+ 穩定度似乎沒什麼問題. 不過... pipy 跟 GitHub release 兩邊列出來的 version 不同步, 要不是剛好要裝一台新 VM 跑 pip install 還真的不會知道, 或許散在各地的文件版本不同步也是造成各種困擾的原因, 小小建議還請海涵 :)

**Comment by Yvictor** [comment]
supported python 3.8
