### ISSUE TITLE
請問這個套件能用在新的逐筆交易制度上嗎

### ISSUE THREAD

**Issue by q10242** [Sinotrade/Shioaji#32]
如題 最近台灣證券交易市場正在改成逐筆交易
這個套件是不是也同樣支援逐筆交易呢？

**Comment by linsamtw** [comment]
https://sinotrade.github.io/tutor/order/Stock_Trade_for_Trade/

逐筆交易後，也可以下單
我有試過

**Comment by ypochien** [comment]
功能已跟交易所逐筆交易同步上線。
