### ISSUE TITLE
查詢歷史Ticks問題

### ISSUE THREAD

**Issue by jason7830** [Sinotrade/Shioaji#33]
![1585124732209](https://user-images.githubusercontent.com/26878981/77516647-b9966a80-6eb5-11ea-8543-9ce484b18f2a.jpg)

如圖上顯示，回傳的ticks除了 ts, volume, close 以外其他欄位都是0

請問這是Code的部分有問題嗎

**Comment by ypochien** [comment]
由於資源規劃，目前還沒有釋出委買、委賣的資訊
之後會針對委買賣資訊提供進行確認，請見諒

**Comment by jason7830** [comment]
謝謝回覆

想在請問一下

place_order掛的委託是否除了透過回傳的物件以外就無法查詢他的委託狀態

且透過官方的證券AP查看委託也是看不到的嗎

Po Chien Yang <notifications@github.com> 於 2020年3月27日 週五 下午9:31寫道：
