### ISSUE TITLE
憑證無法讀取

### ISSUE THREAD

**Issue by utap2001** [Sinotrade/Shioaji#34]
你好
最近用python api下單
登入的時候沒問題
可是發現憑證的讀取出問題
可是我用桌面eleader下單是可以的
不知道是不是套件出問題

![FireShot Capture 066 - sinopac - localhost](https://user-images.githubusercontent.com/36832947/78225363-acecc480-74fc-11ea-9a4b-1fc067fd88f1.jpg)

**Comment by a9202507** [comment]
改成ca_path="Sinopac.pfx" ，然後把憑證跟.py 放同一個目錄試試。
我放同目錄是可以跑的。

**Comment by utap2001** [comment]
後來我有跟工程師聯絡
他們說不要有中文路徑
果然後來這樣程式就可以讀得到了
