### ISSUE TITLE
Option order price is wrong

### ISSUE THREAD

**Issue by elsdrium** [Sinotrade/Shioaji#36]
My sample code is as followed:
```python
contract = api.Contracts.Options.TXO.TXO20200409800C
order = api.Order(action="Buy",
                price=1,
                quantity=1,
                order_type="ROD",
                price_type="LMT",
                octype="Auto",
                account=api.futopt_account)
trade = api.place_order(contract, order)
```

I just tried the order api on TXF and TXO. It seems working properly on TXF. However, the order price that comes out for TXO is absolutely making no sense.
![image](https://user-images.githubusercontent.com/1889188/78598962-d30abf80-7882-11ea-9765-b346fdf73732.png)

Please help to check it. Thanks.

**Comment by elsdrium** [comment]
BTW, I'm using the latest official docker image, **sinotrade/shioaji:latest** with api version 
![image](https://user-images.githubusercontent.com/1889188/78599143-2e3cb200-7883-11ea-86fb-01df427cc3a0.png)

**Comment by luckchiao** [comment]
> My sample code is as followed:
> 
> ```python
> contract = api.Contracts.Options.TXO.TXO20200409800C
> order = api.Order(action="Buy",
>                 price=1,
>                 quantity=1,
>                 order_type="ROD",
>                 price_type="LMT",
>                 octype="Auto",
>                 account=api.futopt_account)
> trade = api.place_order(contract, order)
> ```
> 
> I just tried the order api on TXF and TXO. It seems working properly on TXF. However, the order price that comes out for TXO is absolutely making no sense.
> ![image](https://user-images.githubusercontent.com/1889188/78598962-d30abf80-7882-11ea-9765-b346fdf73732.png)
> 
> Please help to check it. Thanks.

We will confirm and reply.

**Comment by Yvictor** [comment]
@elsdrium 

![image](https://user-images.githubusercontent.com/8242025/78683512-f5074f00-7921-11ea-9da9-a3f73d028d02.png)

![image](https://user-images.githubusercontent.com/8242025/78683727-3d267180-7922-11ea-930d-2bceeeb13cbb.png)


I use the same code like your sample, but the result that i think is correct. Can you give us your seqno to help us check the order log on our server. 

Send to our email victor.yang@sinopac.com, cc: pochien.yang@sinopac.com, fy.lin@sinopac.com, chiao1010.chien@sinopac.com, sam0527.lin@sinopac.com

Thanks
