### ISSUE TITLE
Missing wheel files of python 3.6 and 3.7 windows amd64 for 0.2.0.dev1 on pypi

### ISSUE THREAD

**Issue by Po-haoHuang** [Sinotrade/Shioaji#37]
![020_dev0](https://user-images.githubusercontent.com/5764259/79068134-39666680-7cf7-11ea-988e-0d7e83c2d851.png)

![020_dev1](https://user-images.githubusercontent.com/5764259/79068146-500cbd80-7cf7-11ea-93af-4df253ce0801.png)
Hi,
As first pic showes, there used to be wheel files for python 3.6/3.7 win amd64 on pypi. 
However, for the latest 0.2.0.dev1, there is only python 3.5 wheel for win amd64 as second pic shows.
Is it intended? People using python 3.6 or 3.7 could not install Shioaji on a win amd64 machine for the latest version by pip now.
Could you please check? Thanks.

**Comment by Po-haoHuang** [comment]
Another thing, from pypi I noticed that Shioaji does not provide wheels for 32 bit python. Therefore, for issues like #31 #30, you may want to clarify if user is using 32 bit python on a windows 64 bit machine.
Perhaps you could also specify that Shioaji only supports 64bit python in doc/Readme.
Just my 2 cents.
Thanks.

**Comment by Yvictor** [comment]
fixed it at 0.2.0.dev2
