### ISSUE TITLE
歷史資料的成交明細有誤?

### ISSUE THREAD

**Issue by SteveChen1989** [Sinotrade/Shioaji#38]
例如範例中：
ticks = api.ticks(api.Contracts.Stocks["2330"], "2020-03-04")
結果印出來的bid_price、ask_price、ask_volume、bid_volume均為0
我抓近期的資料也是一樣，
跟看盤軟體顯示的資料都有出入
還麻煩解惑，謝謝。

**Comment by ypochien** [comment]
![image](https://user-images.githubusercontent.com/625016/80616549-a1e17180-8a73-11ea-9401-e77090552235.png)
由於歷史行情在Bid Ask的收集上無法朔及過往，所以目前只能先針對成交Tick的價格做保證
我們會持續加強Bid Ask資料收集，請多包涵

**Comment by ypochien** [comment]
目前資料應該無異狀。
