### ISSUE TITLE
請問有沒有盤後股價資料

### ISSUE THREAD

**Issue by doin43** [Sinotrade/Shioaji#39]
問題 1. 請問有沒有python的指令可以在盤後將當天的股價資料載入?
問題 2. 用api.quote.subscribe()讀取當天的股價後，該怎麼讓資料寫入到txt檔中?
問題 3. 用api.login登入結果出現連不上線的情況，該怎麼處理?

**Comment by ypochien** [comment]
1. 當天的股價 或歷史股價可以透過 api.ticks取得
2. 寫入txt的部分可能得請您看一下 python write file的方法
3. 無法正常登入的部分，有沒有訊息可以貼給我們一下?

**Comment by ypochien** [comment]
先將此issue 關閉，如有任何問題，再請告知
