### ISSUE TITLE
交割銀行餘額抓取

### ISSUE THREAD

**Issue by Win-Jun** [Sinotrade/Shioaji#40]
Hi Shioaji team,
請問有支援交割銀行(永豐銀行)餘額抓取嗎?
謝謝。

**Comment by Win-Jun** [comment]
Hi Shioaji team,
請問有支援交割銀行(永豐銀行)餘額抓取嗎?
謝謝。

**Comment by linsamtw** [comment]
正在開發中

**Comment by linsamtw** [comment]
你好，銀行餘額已開發完畢，
shioaji version: 0.3.0.dev3

使用方法: 

    import shioaji as sj

    api = sj.Shioaji()
    accounts = api.login(person_id=person_id, passwd=passwd)
    account_balance = api.account_balance()
    account_balance
    # [AccountBalance(acc_balance=12345.0, date='2020-07-15 16:26:52', errmsg='')]

**Comment by linsamtw** [comment]
document
https://sinotrade.github.io/tutor/accounting/account_balance/
