### ISSUE TITLE
加權指數資訊、財報資訊

### ISSUE THREAD

**Issue by luanya01** [Sinotrade/Shioaji#42]
建議新增
1.加權指數即時資訊
  ex:大盤預估量、委買委賣、成交筆數等
2.個股財報 (綜合損益表、資產負債表、現金流量表、股利政策表、除權除息結果表、月營收表)

Thanks!

**Comment by ypochien** [comment]
1. 此部分還在排序開發
2. 個股財報部分，可參考 https://github.com/FinMind/FinMind 專案

**Comment by miniyang-dev** [comment]
test
