### ISSUE TITLE
只是subscribe, 就出現 AttributeError: 'NoneType' object has no attribute 'code'

### ISSUE THREAD

**Issue by macleetw** [Sinotrade/Shioaji#44]
Log:

~/python$ ./sub.py
Response Code: 0 | Event Code: 0 | Info: host '203.66.91.161:80', IP 203.66.91.161:80 (host 1 of 1) (host connection attempt 1 of 1) (total connection attempt 1 of 1) | Event: Session up
Ca Initial Done.
Traceback (most recent call last):
  File "./sub.py", line 13, in <module>
    api.quote.subscribe(api.Contracts.Stocks["2614"], quote_type=sj.constant.QuoteType.Tick)
  File "shioaji/backend/solace/api.pyx", line 658, in shioaji.backend.solace.api.SolaceAPI.subscribe
  File "shioaji/backend/solace/api.pyx", line 39, in shioaji.backend.solace.api.contract2topic
AttributeError: 'NoneType' object has no attribute 'code'
Sentry is attempting to send 0 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit

只有照sample code(login的部分正確確) 做以上的subscribe:
api.quote.subscribe(api.Contracts.Stocks["2614"], quote_type=sj.constant.QuoteType.Tick)

環境：
ubuntu 16.04
python3 3.5.2

**Comment by linsamtw** [comment]
請問你的 shioaji 版本是多少?

**Comment by macleetw** [comment]
shioaji             0.2.0.dev9

Package             Version
------------------- ----------------------
certifi             2020.4.5.1
chardet             3.0.4
command-not-found   0.3
idna                2.8
importlib-metadata  1.6.0
language-selector   0.1
loguru              0.4.1
msgpack             1.0.0
pip                 20.1
pycurl              7.43.0
pydantic            1.0
pygobject           3.20.0
pysolace            0.3.3
python-apt          1.1.0b1+ubuntu0.16.4.8
python-debian       0.1.27
python-systemd      231
requests            2.22.0
sentry-sdk          0.14.1
setuptools          20.7.0
shioaji             0.2.0.dev9

**Comment by linsamtw** [comment]
更新就會解決了

**Comment by linsamtw** [comment]
另一種解法

```python
api = sj.Shioaji()
accounts = api.login(person_id=person_id, passwd=passwd, contracts_timeout=100000)
api.quote.subscribe(api.Contracts.Stocks["2614"])
```
