### ISSUE TITLE
希望能增加macosx版本的wheel檔

### ISSUE THREAD

**Issue by r05323028** [Sinotrade/Shioaji#45]
- OS 版本: macOS Catalina 10.15.5
- Python版本: 3.6.10

安裝的時候撞到 `'ERROR: No matching distribution found for shioaji==0.2.1.dev9'`

![截圖 2020-06-16 下午2 15 17](https://user-images.githubusercontent.com/37167503/84738178-05037500-afdc-11ea-89f0-e32e9d465220.png)

查了一下發現應該是沒有打包macosx版本的wheel

![截圖 2020-06-16 下午2 17 28](https://user-images.githubusercontent.com/37167503/84738275-32e8b980-afdc-11ea-87ec-93e33f722dc5.png)

**Comment by Yvictor** [comment]
[0.3.0.dev0](https://github.com/Sinotrade/Shioaji/releases/tag/0.3.0.dev0) added it.
