### ISSUE TITLE
place_order() return Status.Inactive 

### ISSUE THREAD

**Issue by robinsu** [Sinotrade/Shioaji#46]
執行 place_order() 後，trade object 回應 status=OrderStatus(status=<Status.Inactive: 'Inactive'>)，
重新啟動程式執行後是可以成功的。
目前懷疑是程式後 login Session 啟動就放著不動一天後，Session 可能斷掉了，
請問是否有建議如何偵測/判別 Session 狀態，然後重新登入，謝謝。

verison:0.3.0.dev0

**Comment by ypochien** [comment]
目前Token有效期為一天，Token renew的功能還沒做，只能先麻煩您，每天重新登入一次

**Comment by robinsu** [comment]
明白了，謝謝你。
