### ISSUE TITLE
Tick資料沒有內外盤價格

### ISSUE THREAD

**Issue by pm7913** [Sinotrade/Shioaji#50]
通常成交明細不外乎包含:內盤價、外盤價、成交價、成交時間、成交單量

但是使用 api.quote.subscribe(api.Contracts.Stocks["2890"], quote_type='tick')

MKT/redisrd/TSE/2330 {'Close': [239.5], 'Time': '11:11:42.624718', 'VolSum': [12206], 'Volume': [5]}

只有 成交價、時間、單量、總量，缺乏內盤價跟外盤價

建議可以補上

**Comment by ypochien** [comment]
訂閱行情的部分，分成兩塊， quote_type='tick' 是成交的部分
內外盤價格，請參閱 https://sinotrade.github.io/tutor/market_data/streaming/#bidask
是屬於 quote_type='bidask' 的行情訂閱
