### ISSUE TITLE
關於list_position function

### ISSUE THREAD

**Issue by luanya01** [Sinotrade/Shioaji#51]
請問禮拜六主機維護嗎，抓不到未平倉資訊；

另外看API ,get_account_openposition function這個之後會拿掉；
但是list_position取得的資訊無法得知未平倉商品合約月份(code、cond、direction、pnl、price、quantity、yd_quantity) ,
這會導致無法判斷是否到了換倉日而該換倉(也許商品已經是在次月)
請確認，謝謝!

**Comment by ypochien** [comment]
週六公司資料庫有進行異動，造成功能異常，請見諒。

另外針對期貨資訊的處理，現在已列入開發中，會完善整個交易相關資訊，才會將get_account_openposition 拿掉

**Comment by Tingchu** [comment]
請問現在有任何方式能得到期貨持倉部位以及剩餘保證金嗎?
我的期貨帳戶應該有一口未平倉，
但是 api.list_positions(self.api.futopt_account) 回傳 empty list []
而 api.get_account_openposition(query_type='1', account=self.api.futopt_account) 也只回傳 person_id, broker_id, account_id, username 等等

**Comment by Tingchu** [comment]
> > 請問現在有任何方式能得到期貨持倉部位嗎?
> > 我的期貨帳戶應該有一口未平倉，
> > 但是 api.list_positions(self.api.futopt_account) 回傳 empty list []
> > 而 api.get_account_openposition(query_type='1', account=self.api.futopt_account) 也只回傳 person_id, broker_id, account_id, username 等等
> > @ypochien Can somebody help me for this?
> 
> Same issue+1

我後來在Gitter問，有得到解答了：
```
    positions = self.api.get_account_openposition(query_type='0', account=self.api.futopt_account)
    positions = positions.data() # get the list
