### ISSUE TITLE
動態連結程式庫 (DLL) 失敗

### ISSUE THREAD

**Issue by twken** [Sinotrade/Shioaji#52]
更新到3.0以後的版本, import 時會出現 動態連結程式庫 (DLL) 初始化例行程序失敗  的錯誤訊息如下
請問要怎麼修正? 
pysolace    已經有升到       0.9.6

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ken.lin\AppData\Roaming\Python\Python38\site-packages\shioaji\__init__.py", line 26, in <module>
    from shioaji.shioaji import Shioaji
  File "C:\Users\ken.lin\AppData\Roaming\Python\Python38\site-packages\shioaji\shioaji.py", line 10, in <module>
    from shioaji.backend.solace import SolaceAPI
  File "C:\Users\ken.lin\AppData\Roaming\Python\Python38\site-packages\shioaji\backend\solace\__init__.py", line 1, in <module>
    from shioaji.backend.solace.quote import Quote
  File "shioaji\backend\solace\quote.pyx", line 4, in init shioaji.backend.solace.quote
  File "C:\Users\ken.lin\AppData\Roaming\Python\Python38\site-packages\pysolace\__init__.py", line 35, in <module>
    from pysolace import solclient
ImportError: DLL load failed while importing solclient: 動態連結程式庫 (DLL) 初始化例行程序失敗。

**Comment by ypochien** [comment]
我這邊建立python3.8的版本，pip install shioaji 之後是可以正常使用，我跟團隊討論一下，如何協助排除您發生的錯誤
![image](https://user-images.githubusercontent.com/625016/87442064-6abc3e80-c626-11ea-8ce2-d661e2ad9c91.png)

**Comment by ypochien** [comment]
![image](https://user-images.githubusercontent.com/625016/87514836-7272f600-c6ad-11ea-9847-fed52ebcaf37.png)

**Comment by ypochien** [comment]
能否告知您使用的Python版本環境怎麼建立的，以及Windows 的版本

**Comment by sorostu** [comment]
用VS code import shioaji遇到同樣錯誤訊息，請求解答

python版本 3.8.5 64bit
window 10 64位元

**Comment by winthropchang** [comment]
我遇到一樣的問題
由於尚未支持Mac環境
所以我是在MacbookPro上跑windows to go
python: 3.8.5
安裝玩 shioaji 後
主要的問題就是 pysolace 的 DLL 載入失敗
直接 import pysolace 也是一樣的問題

![註解 2020-08-05 005424](https://user-images.githubusercontent.com/5180162/89322047-464c0300-d6b6-11ea-9227-26252161488a.png)

**Comment by winthropchang** [comment]
請問 pysolace 的版本是多少？

**Comment by ypochien** [comment]
請先使用 Anaconda 版本 的 Python ， 目前發現 Windows Store 裡面的Python 會有此 issue.

**Comment by winthropchang** [comment]
目前使用 Anaconda 版本的 Python 可以正常登入以及驗證憑證
不顧你們的說明文件寫的不好
沒有將程式環境說明清楚

**目前你們只能支援的作業系統只有 windows
而且是跑在 Anaconda 環境下面
這些都需要詳詳細細的寫在說明文件之中**

還有標題寫的
**_Shioaji all new cross platform api for trading_** 
這個會讓人誤解可以跨平台
實際上目前只有 windows 而已

**Comment by linsamtw** [comment]
> 目前使用 Anaconda 版本的 Python 可以正常登入以及驗證憑證
> 不顧你們的說明文件寫的不好
> 沒有將程式環境說明清楚
> 
> **目前你們只能支援的作業系統只有 windows 而且是跑在 Anaconda 環境下面 這些都需要詳詳細細的寫在說明文件之中**
> 
> 還有標題寫的
> **_Shioaji all new cross platform api for trading_**
> 這個會讓人誤解可以跨平台
> 實際上目前只有 windows 而已

linux 可以，我有實際在 linux 上使用

**Comment by ypochien** [comment]
> 目前使用 Anaconda 版本的 Python 可以正常登入以及驗證憑證
> 不顧你們的說明文件寫的不好
> 沒有將程式環境說明清楚
> 
> **目前你們只能支援的作業系統只有 windows 而且是跑在 Anaconda 環境下面 這些都需要詳詳細細的寫在說明文件之中**
> 
> 還有標題寫的
> **_Shioaji all new cross platform api for trading_**
> 這個會讓人誤解可以跨平台
> 實際上目前只有 windows 而已

目前 Windows 就是 Windows Store 裡面的 Python3.8 會有 dll loading問題，至於是否得需要用anaconda則不一定， Python 網頁的版本，pipenv的版本都可以正常執行
至於Linux 目前都是正常的、OSX則是卡在憑證還沒弄。

至於跨平台，我們目前確實有客戶已經 在 OSX 用 docker  以及 native linux 上進行交易....
如果您在使用技術上有需要協助的，可以找我們。

**Comment by twken** [comment]
我更新到3.0 後也是失敗? 錯誤如下, 怎麼修正?

D:\MyApp\01.python\stock>python
Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import shioaji
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ken.lin\AppData\Local\Programs\Python\Python38\lib\site-packages\shioaji\__init__.py", line 26, in <module>
    from shioaji.shioaji import Shioaji
  File "C:\Users\ken.lin\AppData\Local\Programs\Python\Python38\lib\site-packages\shioaji\shioaji.py", line 10, in <module>
    from shioaji.backend.solace import SolaceAPI
  File "C:\Users\ken.lin\AppData\Local\Programs\Python\Python38\lib\site-packages\shioaji\backend\solace\__init__.py", line 1, in <module>
    from shioaji.backend.solace.quote import Quote
  File "shioaji\backend\solace\quote.pyx", line 4, in init shioaji.backend.solace.quote
ModuleNotFoundError: No module named 'pysolace'
>>>

**Comment by aowakennomai** [comment]
您好，
請問這個問題有其他建議的處理方式嗎?
我的環境如下:
Windows10 x64 20H2
Python 3.8.9 (from https://www.python.org/downloads/ )
pip 21.0.1
shioaji 0.3.2.dev5
pysolace 0.9.9

#72 這篇雖然有人回文說要降版到 Python 3.7.8
但 Git 專案首頁上有列出支援 Python 3.8 (且 @ypochien 也使用 3.8)
> 我這邊建立python3.8的版本，pip install shioaji 之後是可以正常使用，我跟團隊討論一下，如何協助排除您發生的錯誤
> ![image](https://user-images.githubusercontent.com/625016/87442064-6abc3e80-c626-11ea-8ce2-d661e2ad9c91.png)

所以想請問除了降版以外的處理方式

**Comment by jeff9710109** [comment]
您好
我目前遇到導入問題
想請教您的建議
![image](https://user-images.githubusercontent.com/83211753/116057422-5d51db80-a6b1-11eb-99d7-9798cb2495d3.png)

**Comment by TwEvan** [comment]
請問目前解決3.8版 DLL load failed while importing solclient的問題了嗎？
