### ISSUE TITLE
Mac申請憑證

### ISSUE THREAD

**Issue by winthropchang** [Sinotrade/Shioaji#53]
Mac系統登入之後需要憑證
憑證要去那邊下載呢?

**Comment by ypochien** [comment]
目前MAC 還沒辦法使用憑證.....

**Comment by Yvictor** [comment]
@winthropchang Hi Hi Mac 上建議先用 Docker 之後比較好無痛轉移回 Mac ~~~ 哪一天用 Mac 客戶夠多了我們才有辦法跟公司爭取幫 Mac 使用者買憑證~~~ 我本身也是 Mac 使用者但無奈是奈米戶，公司直接無視我們身為 Mac User 的需求... 
Docker 不會用的話可以看教學 https://www.youtube.com/watch?v=zJ6WbK9zFpI

**Comment by Ed-Yang** [comment]
我也是mac用戶, 一直都是用safari上永豐金理財網(https://www.sinotrade.com.tw/newweb/).

憑證我好像是用 “MAC 總管 (供MAC電腦 申請/更新/查詢憑證)” (https://w3.sinotrade.com.tw/CSCenter/CSCenter_13_3). 很久以前安裝的, 已經忘了詳細是怎麼弄的.

另外, 我嘗試在mac跑Shioaji, 在api.activate_ca時遇到exception:

Exception has occurred: ImportError
cannot import name ca

看起來是內部import ca但是找不到 ca module, 請問: 在mac有試過用其他module代替ca嗎?

**Comment by ychuangab** [comment]
借問一下
ubuntu20.04如何導入憑證？

**Comment by AlexChiang0208** [comment]
我也是mac用戶，在local端的 jupyter lab上一樣會：ImportError: cannot import name ca
但如果用 google colab 是可以登入憑證的（雖然我還沒實際下單過）
