### ISSUE TITLE
sj.data.Kbars  不存在

### ISSUE THREAD

**Issue by rexchwu** [Sinotrade/Shioaji#54]
試著去執行 Tutorial - User Guide;   Market data/Historical Market Data 的 Kbar Data 範例
 
from shioaji.data import Kbars
Kbars??
卻出現以下
Traceback (most recent call last):
  File "<ipython-input-6-c073ea1f6693>", line 1, in <module>
    from shioaji.data import Kbars
ImportError: cannot import name 'Kbars' from 'shioaji.data' (C:\Anaconda3\lib\site-packages\shioaji\data.py)

去查詢 sj.data.Kbar,  
Object `sj.data.Kbar` not found.

Kbar 為何不存在了?

**Comment by rexchwu** [comment]
更新至最新版 0.3.0 dev4 即可,  已解決

**Comment by rexchwu** [comment]
kbars = api.kbars(api.Contracts.Futures.TXF.TXF202008, start="2020-07-21 08:45:00", end="2020-07-27 13:45:00")
df = pd.DataFrame({**kbars})
df.ts = pd.to_datetime(df.ts)
df

   Open     High                  ts      Low  Volume    Close
0    12150.0  12150.0 2020-07-27 09:01:00  12150.0       0  12150.0
1    12150.0  12150.0 2020-07-27 09:02:00  12150.0       0  12150.0
2    12150.0  12150.0 2020-07-27 09:03:00  12150.0       0  12150.0
3    12150.0  12150.0 2020-07-27 09:04:00  12150.0       0  12150.0
4    12150.0  12150.0 2020-07-27 09:05:00  12150.0       0  12150.0
..       ...      ...                 ...      ...     ...      ...
265  12150.0  12150.0 2020-07-27 13:26:00  12150.0       0  12150.0
266  12150.0  12150.0 2020-07-27 13:27:00  12150.0       0  12150.0
267  12150.0  12150.0 2020-07-27 13:28:00  12150.0       0  12150.0
268  12150.0  12150.0 2020-07-27 13:29:00  12150.0       0  12150.0
269  12150.0  12150.0 2020-07-27 13:30:00  12150.0       0  12150.0

不論日期時間怎麼設置, 只能獲得當天資料且時間僅限定在 9:00 - 13:30
如何才能取得多天期的歷史資料, 包含夜盤 ??

**Comment by linsamtw** [comment]
目前只支援現貨的 k 線喔，期貨還在開發中，謝謝
