### ISSUE TITLE
Failed to access bars

### ISSUE THREAD

**Issue by Ed-Yang** [Sinotrade/Shioaji#56]
In JupyterLab, after login and activate CA, there is no problem to access tick data, but failed to access kbars.

Code:

kbars = api.kbars(api.Contracts.Stocks["2330"], start="2020-06-01", end="2020-07-01")
df = pd.DataFrame({**kbars})
df.ts = pd.to_datetime(df.ts)
df

Error:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-65-c1bf896e5f83> in <module>
----> 1 kbars = api.kbars(api.Contracts.Stocks["2330"], start="2020-06-01", end="2020-07-01")
      2 df = pd.DataFrame({**kbars})
      3 df.ts = pd.to_datetime(df.ts)
      4 df

/opt/conda/lib/python3.8/site-packages/shioaji/shioaji.py in kbars(self, contract, start, end, timeout, cb)
    573             end (str): "2020-06-02"
    574         """
--> 575         kbars = self._solace.kbars(contract, start, end, timeout, cb)
    576         return kbars
    577 

shioaji/backend/solace/api.pyx in shioaji.backend.solace.api.SolaceAPI.kbars()

shioaji/backend/solace/api.pyx in shioaji.backend.solace.api.SolaceAPI._kbars_cb()

/opt/conda/lib/python3.8/site-packages/shioaji/utils.py in raise_resp_error(status_code, resp)
     41 def raise_resp_error(status_code: int, resp: dict):
     42     log.error(resp)
---> 43     detail = resp.get("response", {}).get("detail", "")
     44     if status_code == 401:
     45         raise TokenError(status_code, detail)

AttributeError: 'str' object has no attribute 'get'

**Comment by linsamtw** [comment]
已修復

**Comment by Ed-Yang** [comment]
剛測試過, 沒問題了, 謝謝!

**Comment by Ed-Yang** [comment]
又不行了.....


---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-28-700c5a490c77> in <module>
      1 import pandas as pd
----> 2 kbars = api.kbars(api.Contracts.Stocks["2330"], start="2020-06-01", end="2020-07-01")
      3 df = pd.DataFrame({**kbars})
      4 df.ts = pd.to_datetime(df.ts)
      5 df

/opt/conda/lib/python3.8/site-packages/shioaji/shioaji.py in kbars(self, contract, start, end, timeout, cb)
    573             end (str): "2020-06-02"
    574         """
--> 575         kbars = self._solace.kbars(contract, start, end, timeout, cb)
    576         return kbars
    577 

shioaji/backend/solace/api.pyx in shioaji.backend.solace.api.SolaceAPI.kbars()

shioaji/backend/solace/api.pyx in shioaji.backend.solace.api.SolaceAPI._kbars_cb()

/opt/conda/lib/python3.8/site-packages/shioaji/utils.py in raise_resp_error(status_code, resp)
     47         raise SystemMaintenance(status_code, detail)
     48     else:
---> 49         raise Exception(resp)

Exception: {}

**Comment by Ed-Yang** [comment]
cannot reproduce in 0.3.0.dev6.
