### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Ed-Yang** [Sinotrade/Shioaji#57]
關於：
api.quote.subscribe(api.Contracts.Stocks["2330"], quote_type="tick")
api.quote.subscribe(api.Contracts.Stocks["2330"], quote_type="bidask")

我是股市新手, 可否加說明 quote_type "tick" vs "bidask" 的資料有何不同 ??

另外, what is "short stock source" ?? (https://sinotrade.github.io/tutor/market_data/short_stock_source/)

**Comment by linsamtw** [comment]
tick 是 成交價，
bidask 包含上下五檔，
舉例來說，

tick

    MKT/redisrd/TSE/2330 {'Close': [239.5], 'Time': '11:11:42.624718', 'VolSum': [12206], 'Volume': [5]}


bidask

	QUT/redisrd/TSE/2330 {'AskPrice': [240.0, 240.5, 241.0, 241.5, 242.0], 'AskVolume': [1808, 1789, 1645, 582, 1170], 'BidPrice': [239.5, 239.0, 238.5, 238.0, 237.5], 'BidVolume': [204, 765, 389, 475, 359], 'Date': '2019/03/18', 'Time': '11:11:42.624718'}

**Comment by Ed-Yang** [comment]
謝謝！

"short stock source" 是什麼？

 (https://sinotrade.github.io/tutor/market_data/short_stock_source/)

**Comment by linsamtw** [comment]
在股票交易裡面，short 代表做空，source 代表資源，

short stock source 就是或有券源，你如果要借券放空，有多少券可以借的意思

**Comment by Ed-Yang** [comment]
暸解了, 感恩！
