### ISSUE TITLE
list_trade return inconsistent data

### ISSUE THREAD

**Issue by Ed-Yang** [Sinotrade/Shioaji#59]
There are two submitted order, try to list all trades, but the API return different object type for 'contract'.

Just curious if this behavior is correct or not.

for tr in api.list_trades():
    print(type(tr.contract))

Result:

<class 'shioaji.contracts.Stock'>
<class 'shioaji.contracts.Contract'> <-- this '.Contract' class has no 'name' variable

**Comment by linsamtw** [comment]
> There are two submitted order, try to list all trades, but the API return different object type for 'contract'.
> 
> Just curious if this behavior is correct or not.
> 
> for tr in api.list_trades():
> print(type(tr.contract))
> 
> Result:
> 
> <class 'shioaji.contracts.Stock'>
> <class 'shioaji.contracts.Contract'> <-- this '.Contract' class has no 'name' variable


<class 'shioaji.contracts.Contract'> <-- this '.Contract' class has no 'name' variable
這是哪個股票 id?

**Comment by Ed-Yang** [comment]
2489

**Comment by linsamtw** [comment]
https://gitter.im/Sinotrade/Shioaji?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

這我們的聊天室，我們直接在上面討論好了，會比較即時

**Comment by Ed-Yang** [comment]
OK

**Comment by Ed-Yang** [comment]
After logout and login again, all records are in consistent format.
