### ISSUE TITLE
請問有辦法取得所有可交易商品的 Symbol?

### ISSUE THREAD

**Issue by kangchihlun** [Sinotrade/Shioaji#6]

**Comment by Yvictor** [comment]
https://github.com/Sinotrade/Shioaji#using-tab-to-direct-get-avaliable-trading-product-with-contracts

![contracts](https://user-images.githubusercontent.com/8242025/55205336-64c20480-520d-11e9-94e5-f39e643555d7.png)

目前的看可以交易的商品用法是像這樣
但是如果需要提供一個list_avaliable_contracts這樣的function也是ok的
不過考量到商品非常多
這部分可能還是會有分層的需求
