### ISSUE TITLE
install shiaoji error message

### ISSUE THREAD

**Issue by Ten510** [Sinotrade/Shioaji#60]
用anaconda prompt安裝時出現下列訊息，是否有解決方法?

ERROR: pytest-astropy 0.8.0 requires pytest-cov>=2.0, which is not installed.
ERROR: pytest-astropy 0.8.0 requires pytest-filter-subpackage>=0.1, which is not installed.

Installing collected packages: importlib-metadata, shioaji
  Attempting uninstall: importlib-metadata
    Found existing installation: importlib-metadata 1.5.0
    Uninstalling importlib-metadata-1.5.0:

ERROR: Could not install packages due to an EnvironmentError: [WinError 5] 存取被拒。: 'c:\\programdata\\anaconda3\\lib\\site-packages\\importlib_metadata-1.5.0.dist-info\\INSTALLER'
Consider using the `--user` option or check the permissions.

**Comment by ypochien** [comment]
由於Windows下 對於預設的Python目錄有權限控管，所以請使用
新安裝請使用 `pip install --user shioaji`
更新版本請使用 `pip install --user -U shioaji`
