### ISSUE TITLE
ImportError: cannot import name ca

### ISSUE THREAD

**Issue by vgvgvg12321** [Sinotrade/Shioaji#62]
Hi 

目前使用mac OS 10.15.7, 並且用jupyter lab 執行shioaji 匯入憑證。但目前遇到一個ImportError: cannot import name ca   一直解決不了，有人可以協助我嗎？

<img width="1130" alt="截圖 2020-10-05 下午11 13 36" src="https://user-images.githubusercontent.com/72401130/95097910-9b60cf80-0760-11eb-8446-be676171e829.png">

謝謝

**Comment by Yvictor** [comment]
macOS currently not support CA. When import Shioaji will show this warning message.

**Comment by vgvgvg12321** [comment]
When do you will fix this issue?
