### ISSUE TITLE
Streaming 報價有問題

### ISSUE THREAD

**Issue by macleetw** [Sinotrade/Shioaji#63]
Code:
----------------------------------------------------------------------------
import shioaji as sj

api = sj.Shioaji()
accounts = api.login("m_account", "my_password")

def quote_callback(topic: str, quote: dict):
    print(f"Topic: {topic}, Quote: {quote}")

def event_callback(resp_code: int, event_code: int, info: str, event: str):
        print(f'Event code: {event_code} | Event: {event}')

api.quote.set_quote_callback(quote_callback)
api.quote.set_event_callback(event_callback)
api.quote.subscribe(api.Contracts.Stocks["2614"], quote_type="tick")
----------------------------------------------------------------------------

執行結果：
Response Code: 0 | Event Code: 0 | Info: host '203.66.91.161:80', IP 203.66.91.161:80 (host 1 of 1) (host connection attempt 1 of 1) (total connection attempt 1 of 1) | Event: Session up
Event code: 16 | Event: Subscribe or Unsubscribe ok

程式就結束了，沒有傳回任何報價或event
請問是那裏有問題？

API的版本:
shioaji             0.3.0.dev9

Linux:
ubuntu 16.04

**Comment by Yvictor** [comment]
main thread exit when the main thread job finish
keep the main thread block you can use
``` python
from threading import Event

# ...

block = Event()
block.wait()
```

**Comment by macleetw** [comment]
Thanks!
I will try.
