### ISSUE TITLE
Shioaji 的發展計畫 - v0.3.0.dev9 之後

### ISSUE THREAD

**Issue by ypochien** [Sinotrade/Shioaji#65]
釋出請參考 [Change log](https://sinotrade.github.io/release/)

- v0.3.0
  * [x]   交易
    * [x] 支援盤中零股交易-[說明文件](https://sinotrade.github.io/tutor/order/IntradayOdd/)(2020/10/26上路)
  * [x] 行情
    * [x] 盤中零股交易

- v0.4.0
  * [ ] 行情
    * [ ] 重構報價介面
    * [ ] K線訂閱
    * [ ] ticks 資料區間查詢

- In plan
  * [ ] shioaji C# version
  * [ ] 興櫃
  * [ ] 期貨帳務重構

**Comment by weretyczx** [comment]
HI 
有沒有考慮走 web api 方式
而不限定開發的語言呢?

**Comment by honeymagico** [comment]
建議不要把精力花在C#上, 
把這專案完善才是重點, C#有太多方式可以調用PYTHON完成工作, 而且不難,

若真要發展新版本, 請考慮底層一點的非託管式C/C++生成動態連結庫, 才方便各種語言平台都能調用,
