### ISSUE TITLE
what is TickType?

### ISSUE THREAD

**Issue by daf11865** [Sinotrade/Shioaji#66]
請問即時報價中的TickType是指什麼呢

        date             Time      Close Volume futopt_id  TickType
0  2020/05/16  04:58:01.867000  [10737.0]    [1]     TXFE0         1
1  2020/05/16  00:57:21.057000  [10714.0]    [1]     TXFE0         2

**Comment by martinachuang** [comment]
內外盤

> 請問即時報價中的TickType是指什麼呢
> 
> ```
>     date             Time      Close Volume futopt_id  TickType
> ```
> 
> 0 2020/05/16 04:58:01.867000 [10737.0] [1] TXFE0 1
> 1 2020/05/16 00:57:21.057000 [10714.0] [1] TXFE0 2
