### ISSUE TITLE
希望 api.kbars 支援 日K

### ISSUE THREAD

**Issue by JasonYao81000** [Sinotrade/Shioaji#68]
api.kbars 目前只提供 1分K
希望 api.kbars 支援 日K
感謝

**Comment by linsamtw** [comment]
目前沒有提供日K
可以先參考這個 [https://finmind.github.io/tutor/TaiwanMarket/Technical/#taiwanstockprice](https://finmind.github.io/tutor/TaiwanMarket/Technical/#taiwanstockprice)，這有提供日成交資訊

**Comment by Chenyu-Tsai** [comment]
分享不使用 FinMind 的方法
# 原版 1 分 k 範例
df = pd.DataFrame({**kbars})
df.ts = pd.to_datetime(df.ts)
# 轉為日 k 
df.ts = df.ts.dt.date
df.index = pd.to_datetime(df.ts)
day_df = df.resample('D').agg({'Open': 'first', 'High': 'max', 'Low': 'min', 'Close': 'last'}).dropna()

有更好的解法或有錯還請告知XDD
