### ISSUE TITLE
Fail to install on python 3.8.5

### ISSUE THREAD

**Issue by finaccoun** [Sinotrade/Shioaji#74]
(py38) D:\Anaconda3>pip install shioaji
ERROR: Could not find a version that satisfies the requirement shioaji
ERROR: No matching distribution found for shioaji

**Comment by linsamtw** [comment]
請用 64 位元的 python

![image](https://user-images.githubusercontent.com/20013414/103187513-83cc5980-48ff-11eb-8f28-88a62e995283.png)
