### ISSUE TITLE
以api.kbars取得最近一個營業日每分鐘走勢時，資料框內資料會重複一輪

### ISSUE THREAD

**Issue by hamsterLiao** [Sinotrade/Shioaji#75]
以api.kbars取得最近一個營業日每分鐘走勢時

```python
kbars = api.kbars(api.Contracts.Stocks["2454"], start="2020-12-25", end="2020-12-25")
df = pd.DataFrame({**kbars})

```
若start與end皆為最近一個營業日資料時, 回傳結果會多了一倍的資料(每小時60分 * 4.5小時 = 270), 每個時間點都會重複兩筆

```
  | ts | High | Volume | Low | Open | Close
-- | -- | -- | -- | -- | -- | --
2020-12-25 10:15:00 | 16.30 | 7 | 16.30 | 16.30 | 16.30
2020-12-25 10:16:00 | 16.30 | 0 | 16.30 | 16.30 | 16.30
2020-12-25 10:17:00 | 16.30 | 0 | 16.30 | 16.30 | 16.30
2020-12-25 10:18:00 | 16.30 | 0 | 16.30 | 16.30 | 16.30
2020-12-25 10:19:00 | 16.30 | 0 | 16.30 | 16.30 | 16.30
... | ... | ... | ... | ... | ...
2020-12-25 13:26:00 | 16.45 | 0 | 16.45 | 16.45 | 16.45
2020-12-25 13:27:00 | 16.45 | 0 | 16.45 | 16.45 | 16.45
2020-12-25 13:28:00 | 16.45 | 0 | 16.45 | 16.45 | 16.45
2020-12-25 13:29:00 | 16.45 | 0 | 16.45 | 16.45 | 16.45
2020-12-25 13:30:00 | 16.45 | 0 | 16.45 | 16.45 | 16.45
540 rows × 6 columns
```

如果是最近一個營業日之前的日期, 數量會正常, 不會重複
`270 rows × 6 columns`

**Comment by linsamtw** [comment]
@ypochien

**Comment by hamsterLiao** [comment]
shioaji==0.3.1.dev8

```
kbars = api.kbars(api.Contracts.Stocks["2454"], start="2021-01-12", end="2021-01-12")
df = pd.DataFrame({**kbars})
df['dt'] = pd.to_datetime(df.ts)
```
指定查詢2021-01-12, 但跑出2021-01-13的資料, 挺困擾的...

Close | Low | Open | High | Volume | ts | dt
-- | -- | -- | -- | -- | -- | --
854.0 | 853.0 | 857.0 | 858.0 | 799 | 1610442060000000000 | 2021-01-12 09:01:00
854.0 | 853.0 | 853.0 | 856.0 | 122 | 1610442120000000000 | 2021-01-12 09:02:00
856.0 | 854.0 | 854.0 | 857.0 | 93 | 1610442180000000000 | 2021-01-12 09:03:00
861.0 | 857.0 | 857.0 | 862.0 | 204 | 1610442240000000000 | 2021-01-12 09:04:00
865.0 | 861.0 | 861.0 | 865.0 | 236 | 1610442300000000000 | 2021-01-12 09:05:00
... | ... | ... | ... | ... | ... | ...
884.0 | 884.0 | 884.0 | 884.0 | 0 | 1610544360000000000 | 2021-01-13 13:26:00
884.0 | 884.0 | 884.0 | 884.0 | 0 | 1610544420000000000 | 2021-01-13 13:27:00
884.0 | 884.0 | 884.0 | 884.0 | 0 | 1610544480000000000 | 2021-01-13 13:28:00
884.0 | 884.0 | 884.0 | 884.0 | 0 | 1610544540000000000 | 2021-01-13 13:29:00
884.0 | 884.0 | 884.0 | 884.0 | 776 | 1610544600000000000 | 2021-01-13 13:30:00

**Comment by ypochien** [comment]
@hamsterLiao fixed... thank you
