### ISSUE TITLE
2021-01-11 大盤跟期貨資料皆不正確

### ISSUE THREAD

**Issue by gilibaby** [Sinotrade/Shioaji#76]
<img width="774" alt="截圖 2021-01-11 下午3 03 17" src="https://user-images.githubusercontent.com/1842133/104153814-4a770c00-541e-11eb-8c7f-cc3a51030e13.png">

**Comment by gilibaby** [comment]
爛透了，有問題反應了也沒人處理，連兩天了
<img width="752" alt="截圖 2021-01-12 下午4 09 34" src="https://user-images.githubusercontent.com/1842133/104287043-dbb6b300-54f0-11eb-911e-14c231ffb950.png">

**Comment by linsamtw** [comment]
目前不支援期貨跟指數 K 線

**Comment by gilibaby** [comment]
感謝通知，那我抓 ticks 重組

import pandas as pd

td = data.set_index(pd.DatetimeIndex(pd.to_datetime(data["ts"])))
td = td["close"].resample('1T').ohlc()
td.dropna(axis=0, how='all', inplace=True)
td = td.reset_index()

以上，給有需要的人參考。
