### ISSUE TITLE
Token多久逾期與錯誤代碼說明

### ISSUE THREAD

**Issue by hamsterLiao** [Sinotrade/Shioaji#80]
請問

1. Token多久逾期, 以及是否會有後踢前的限制?
2. 文件是否能增加錯誤代碼表, 以利error handling

Thanks!

**Comment by linsamtw** [comment]
> 請問
> 
> 1. Token多久逾期, 以及是否會有後踢前的限制?

一天，無後踢前限制

> 2. 文件是否能增加錯誤代碼表, 以利error handling
> Thanks!

這部分我回報團隊討論看看

**Comment by john24318** [comment]
您好，順便請問
1. 開發流程有無符合軟體(ISO, OWASP, NIST)與金融法規規範?
2. 每次release新版有跑過那些測試?
3. server用哪些漏洞軟體掃過?
4. 若API改版幾天前會預先告知客戶? 怎麼告知?
5. 有無Line群或irc?
謝謝!

**Comment by ypochien** [comment]
> 您好，順便請問
> 
> 1. 開發流程有無符合軟體(ISO, OWASP, NIST)與金融法規規範?
> 2. 每次release新版有跑過那些測試?
> 3. server用哪些漏洞軟體掃過?
> 4. 若API改版幾天前會預先告知客戶? 怎麼告知?
> 5. 有無Line群或irc?
>    謝謝!

1. 公司有導入ISO27001資安規範 以及 主管機關規範
2. release 會經過 我們開發的測試流程
3. 公司都有針對各系統服務與程式碼，進行弱點、漏洞掃描
4.  目前只有放出changelog 都在說明網頁上
5. 目前提供 github issue (here) 以及 gitter ，fb 社團 與 telegram群組
不客氣

P.S 如果對於安全性有疑慮，建請使用別家的服務 :)
