### ISSUE TITLE
請問Login Token如何進行更新

### ISSUE THREAD

**Issue by JimmyOnArch** [Sinotrade/Shioaji#81]
您好，
請問Login Token如何進行更新，
確保Session不會斷線或出現錯誤。

**Comment by linsamtw** [comment]
時效一天，每天重登入即可

**Comment by JimmyOnArch** [comment]
請問如果程式不想中斷，直接再進行一次api.login即可嗎?
目前程式定期發動 api.login 但出現連線過多的錯誤。

**Comment by JimmyOnArch** [comment]
> 時效一天，每天重登入即可
@linsamtw 
請問如果程式不想中斷，直接再進行一次api.login即可嗎?
目前程式定期發動 api.login 但出現連線過多的錯誤。
