### ISSUE TITLE
請問如何結合Vnpy ? 需要詳細的流程,謝謝!

### ISSUE THREAD

**Issue by going1122** [Sinotrade/Shioaji#82]
網路上發現這個https://blog.alvin.tw/Shioaji-With-Vnpy/
,但一直無法成功

再麻煩提供解決方法或流程,感謝 !

**Comment by linsamtw** [comment]
@ypochien

**Comment by ypochien** [comment]
已心力交瘁，無力跟版
推薦 https://mastertalks.tw/products/vnpy
