### ISSUE TITLE
無法import Shioaji

### ISSUE THREAD

**Issue by Marshors** [Sinotrade/Shioaji#84]
請問一下  我是安裝anaconda, python 版本3.8.5, 使用spyder

在 pip install shioaji 後
嘗試使用spyder import shioaji as sj
會出現下列錯誤:

  File "C:\Users\Mar\anaconda3\lib\site-packages\shioaji\__init__.py", line 23, in <module>
    inject_libpath()

  File "C:\Users\Mar\anaconda3\lib\site-packages\shioaji\__init__.py", line 17, in inject_libpath
    os.add_dll_directory(libs_path.as_posix())

  File "C:\Users\Mar\anaconda3\lib\os.py", line 1109, in add_dll_directory
    cookie = nt._add_dll_directory(path)

OSError: [WinError 127] 找不到指定的程序。: 'C:/Users/Mar/anaconda3/lib/site-packages/shioaji/.libs'

請問是哪裡沒安裝好嗎?

**Comment by Marshors** [comment]
安裝後,在site pakage的folder 有shioaji的資料夾。
不知道為何無法import
安裝時的內容:

Collecting shioaji
  Using cached shioaji-0.3.1.dev8-cp38-cp38-win_amd64.whl (1.8 MB)
Requirement already satisfied: requests==2.22.0 in c:\users\mar\anaconda3\lib\si
te-packages (from shioaji) (2.22.0)
Requirement already satisfied: pysolace==0.9.8 in c:\users\mar\anaconda3\lib\sit
e-packages (from shioaji) (0.9.8)
Requirement already satisfied: pydantic==1.0.0 in c:\users\mar\anaconda3\lib\sit
e-packages (from shioaji) (1.0)
Requirement already satisfied: xxhash==2.0.0 in c:\users\mar\anaconda3\lib\site-
packages (from shioaji) (2.0.0)
Requirement already satisfied: loguru==0.4.1 in c:\users\mar\anaconda3\lib\site-
packages (from shioaji) (0.4.1)
Requirement already satisfied: importlib-metadata==1.6.0 in c:\users\mar\anacond
a3\lib\site-packages (from shioaji) (1.6.0)
Requirement already satisfied: sentry-sdk==0.14.1 in c:\users\mar\anaconda3\lib\
site-packages (from shioaji) (0.14.1)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\use
rs\mar\anaconda3\lib\site-packages (from requests==2.22.0->shioaji) (1.25.11)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mar\anaconda3\lib\
site-packages (from requests==2.22.0->shioaji) (2020.6.20)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\mar\anaconda3\l
ib\site-packages (from requests==2.22.0->shioaji) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\mar\anaconda3\lib\site
-packages (from requests==2.22.0->shioaji) (2.8)
Requirement already satisfied: msgpack in c:\users\mar\anaconda3\lib\site-packag
es (from pysolace==0.9.8->shioaji) (1.0.0)
Requirement already satisfied: orjson==3.3.1 in c:\users\mar\anaconda3\lib\site-
packages (from pysolace==0.9.8->shioaji) (3.3.1)
Requirement already satisfied: win32-setctime>=1.0.0; sys_platform == "win32" in
 c:\users\mar\anaconda3\lib\site-packages (from loguru==0.4.1->shioaji) (1.0.3)
Requirement already satisfied: colorama>=0.3.4; sys_platform == "win32" in c:\us
ers\mar\anaconda3\lib\site-packages (from loguru==0.4.1->shioaji) (0.4.4)
Requirement already satisfied: zipp>=0.5 in c:\users\mar\anaconda3\lib\site-pack
ages (from importlib-metadata==1.6.0->shioaji) (3.4.0)
Installing collected packages: shioaji
Successfully installed shioaji-0.3.1.dev8
(base) PS C:\Users\Mar>

**Comment by linsamtw** [comment]
![image](https://user-images.githubusercontent.com/20013414/109610039-2f479380-7b67-11eb-979c-ab147a7cb4f2.png)
方便截圖嗎?
