### ISSUE TITLE
api document

### ISSUE THREAD

**Issue by hlogit** [Sinotrade/Shioaji#85]
請問有完整的api document 嗎?

**Comment by linsamtw** [comment]
https://sinotrade.github.io/

**Comment by hlogit** [comment]
https://automation.deepsecurity.trendmicro.com/article/20_0/api-reference/
這個比較像樣一點吧，謝謝

**Comment by Yvictor** [comment]
@hlogit 
我們不是走 http 的 protocol，有 openapi doc 但目前只針對社群協助開發夥伴公開。
https://sinotrade.github.io/ShioajiOpenAPI/

另外你覺得的像樣，你可以比較趨勢跟永豐的薪水以後，再來說像不像樣，畢竟領多少錢做多少事。
資訊處主管認為永豐不是軟體公司，所以沒辦法，我也是做自己爽的謝謝。

**Comment by hlogit** [comment]
對不起，冒犯了，是我搞不清楚。
以我這外行人看起來，你在永豐做爽的應該是曲材了。
我不在趨勢，也不在永豐，無法比較 薪水
目前的 類openapi doc看來很好，公不公開我不知道。
感謝
