### ISSUE TITLE
市價委託單

### ISSUE THREAD

**Issue by ian15937** [Sinotrade/Shioaji#87]
Guide裡似乎沒有市價的委託單
請問是否有這功能呢 如果沒有的話希望可以新增
對停損來說這功能滿重要的

**Comment by linsamtw** [comment]
> Guide

https://sinotrade.github.io/tutor/order/Stock/#order-object

![image](https://user-images.githubusercontent.com/20013414/109745315-a3894200-7c0e-11eb-8efd-de97f00afe5f.png)

LMT: 限價單
MKT: 市價單
MKP: 範圍市價

**Comment by ian15937** [comment]
那請問price應該填什麼呢

**Comment by linsamtw** [comment]
你填0就好，可以先在測試機上做下單測試

**Comment by ian15937** [comment]
那市價單的order_type應該要填什麼呢 填ROD會被退"當日市價單不允許當日有效委託(ROD)"
