### ISSUE TITLE
Tick資料有錯誤?

### ISSUE THREAD

**Issue by AngelicKoneko** [Sinotrade/Shioaji#89]
抓資料時會發現像這樣的錯誤。
![image](https://user-images.githubusercontent.com/58766474/110339861-98e20900-8063-11eb-9321-1bd82131e9a6.png)
這是轉換後的
![image](https://user-images.githubusercontent.com/58766474/110340030-c5962080-8063-11eb-989e-c6cbbdbf7b62.png)

還蠻常發生的，請問這是什麼原因??

例如:
api.ticks(api.Contracts.Stocks["2328"], "2018-12-10")

謝謝

**Comment by linsamtw** [comment]
什麼錯誤?

**Comment by AngelicKoneko** [comment]
1. api.ticks(api.Contracts.Stocks["2328"], "2018-12-10")
用這個指令撈到的資料，同一天給兩次。

2.api.ticks(api.Contracts.Stocks["2328"], "2020-03-05")
這個則是時間序錯誤。中間插入了14:30的資料。
![image](https://user-images.githubusercontent.com/58766474/110440987-3b49cd00-80f4-11eb-907e-062b53d5b892.png)

**Comment by AngelicKoneko** [comment]
api.ticks(api.Contracts.Stocks["2328"], "2020-03-06")
這個也是資料錯誤，13:30的資料多給了一次，14:30資料消失。
![image](https://user-images.githubusercontent.com/58766474/110441426-b8754200-80f4-11eb-9d9e-5b1112eaa32f.png)

**Comment by ypochien** [comment]
我會針對資料重複的做一次資料清洗動作，請見諒

**Comment by twken** [comment]
> api.ticks(api.Contracts.Stocks["2328"], "2020-03-06")
> 這個也是資料錯誤，13:30的資料多給了一次，14:30資料消失。
> ![image](https://user-images.githubusercontent.com/58766474/110441426-b8754200-80f4-11eb-9d9e-5b1112eaa32f.png)

你好, 請教是怎麼把 ts 轉成時間的?

**Comment by hannah-cheng** [comment]
您好, 我也在歷史資訊遇上相同問題, 請問若是即時資訊也會遇到嗎? 有點擔心這樣做自動化交易可能會出錯QQ
