### ISSUE TITLE
程式登出後 api.list_trades() 未包含先前的掛單

### ISSUE THREAD

**Issue by OppOops** [Sinotrade/Shioaji#9]
## 問題描述
程式登出或是 api 物件重新生成(多重登入)時，呼叫 api.list_trades() 未顯示當日的掛單。 若使用 api.update_status() 也無法顯示掛單。

## 預期回傳
list_trades() 應該要包含當日的進出，否則這對部分操作示會有影響的。舉例來說，在這狀況下使用 cancel_order() 是不太方便的，由於該函示要求傳入 trade 物件 (而非order id)，但文件上並沒有提到 trade 物件如何生成，最終導致無法撤單。

## 可能的後果 (以撤單為例)
如果沒撤單會造成保證金無法利用，或是無法改單而產生虧損。

## 建議解決方式 (擇一即可)
1. remote/local 端紀錄 order 資訊，在登入的時候生成 trade/order 物件。
2. 公開 https/restful 接口給其他人使用。
3. 提供 trade 物件__init__方法，交由 client 自行記錄 id 等資訊。
4. 實作其他 method 如 fetch_orders() 直接查詢當日所有交易。

<del>p.s. 以類似 monkey patch 的方式當然是可以處理的，不過稍嫌麻煩。</del>
p.s. 使用 monkey patch 可能會造成原本的 order 亦無法撤單，請勿嘗試。

**Comment by Yvictor** [comment]
感謝你的建議，我們會把list_trades也加上當日的進出。

**Comment by Yvictor** [comment]
已修正
