### ISSUE TITLE
是否提供融券的功能？

### ISSUE THREAD

**Issue by johney4415** [Sinotrade/Shioaji#91]
想問一下目前是否有提供先賣後買的功能（融券）？

**Comment by linsamtw** [comment]
當沖有先賣這個選項
https://sinotrade.github.io/tutor/order/Stock/#first-sell

當天先賣後買，就會自動轉融資融券

**Comment by ypochien** [comment]
補充一下 先賣後買的部分分兩種
如果你是現股，就是看標的當天是否有 先賣後買 (當沖) 的狀態
如果你是先融券 / 後融資 回補做當沖，這就是看有無資券的限制

當然，做券賣資買的當沖成本高了點，是可以電話請營業員幫你轉成現股當沖。
唯有這個交易種類的轉換 需人工介入，下單本身，API 都可以進行委託
