### ISSUE TITLE
order callback

### ISSUE THREAD

**Issue by ian15937** [Sinotrade/Shioaji#93]
order callback收到成交回報時
其中有一個key是'exchange_seq'
請問這是否對應了委託單回報'order'裡面的'seqno'呢?
如果不是的話 是否有辦法連結成交單與委託單

例如從成交單就能知道是哪張委託單成交的

另外在Order Object裡面的OrderStatus的deals的形式為何?
是否也能拿來連結成交單與委託單呢

**Comment by ypochien** [comment]
在callback中 有分 Order 與 Deal ，可以透過其中的seqno屬性作對應

並且可以跟OrderStatus裡面的deals 的seq 屬性作對應，

之後我們會修正OrderStatus的 Deals 屬性名稱 一致改為seqno

**Comment by ian15937** [comment]
所以Deal callback裡的exchange_seq會等於某張訂單的'seqno'囉?
