### ISSUE TITLE
Sonipec－VNPY 測試帳號登入問題

### ISSUE THREAD

**Issue by tungp03** [Sinotrade/Shioaji#94]
不好意思想問一下，我測試帳號登入時會跑出這個畫面
![image](https://user-images.githubusercontent.com/32927761/112852324-66658200-90de-11eb-8660-1c4d6c62e58b.png)
想請問要怎麼解決?

**Comment by ypochien** [comment]
當時試著整合到vnpy的版本所使用的function，有進行過修正，vnpy取用的部分也得做更改。

唯vnpy gateway為我個人進行的side project，非公司支援，故無法在這邊協助進行
