### ISSUE TITLE
訂閱的tick及bidask會愈來愈慢

### ISSUE THREAD

**Issue by ian15937** [Sinotrade/Shioaji#96]
如題 大約只訂閱了10檔的tick與bidask

但是看到來的訊息跟現實時間差愈差愈多 愈來愈慢

請問是訂閱的數量太多的關係嗎

如果是應該怎麼開啟這個上限呢

**Comment by linsamtw** [comment]
你的網速問題，訂閱越多，等於我們發送越多資訊到你的電腦，如果網速不夠，很容易變慢

**Comment by ian15937** [comment]
可是我的網路頻寬是1G

**Comment by ian15937** [comment]
> 你的網速問題，訂閱越多，等於我們發送越多資訊到你的電腦，如果網速不夠，很容易變慢

可是我的網路頻寬是1G

**Comment by linsamtw** [comment]
> > 你的網速問題，訂閱越多，等於我們發送越多資訊到你的電腦，如果網速不夠，很容易變慢
> 
> 可是我的網路頻寬是1G

https://fast.com/zh/tw/

方便幫我們用這個測一下網速嗎?

**Comment by KN16H7** [comment]
我有碰過的狀況是, 一台 vm (光世代 400M 的固一 IP 被中華電信鎖在 100M) 跟原 po 一樣接 tick/bidask 10 檔 (大台/小台 * 近月/次月 另加 大盤), callback 收到資料之後處理的程式碼不太漂亮, 處理資料結構/計算的過程中有拖到, 所以後面收到的資料就愈拖愈長. 修完程式之後平均每一筆資料進來的處理時間都小於 0.0001 秒. 或許可以測試一下, callback 收到資料直接吐 row data 到 log file 會不會發生一樣的問題.

**Comment by ian15937** [comment]
> > > 你的網速問題，訂閱越多，等於我們發送越多資訊到你的電腦，如果網速不夠，很容易變慢
> > 
> > 
> > 可是我的網路頻寬是1G
> 
> https://fast.com/zh/tw/
> 
> 方便幫我們用這個測一下網速嗎?

下載150Mbps
上傳84Mbps

這是內網的速度 對外應該有1G

**Comment by ian15937** [comment]
> 我有碰過的狀況是, 一台 vm (光世代 400M 的固一 IP 被中華電信鎖在 100M) 跟原 po 一樣接 tick/bidask 10 檔 (大台/小台 * 近月/次月 另加 大盤), callback 收到資料之後處理的程式碼不太漂亮, 處理資料結構/計算的過程中有拖到, 所以後面收到的資料就愈拖愈長. 修完程式之後平均每一筆資料進來的處理時間都小於 0.0001 秒. 或許可以測試一下, callback 收到資料直接吐 row data 到 log file 會不會發生一樣的問題.

我的情況是偶發性的
有時候會發生 有時候不會

**Comment by linsamtw** [comment]
> > 我有碰過的狀況是, 一台 vm (光世代 400M 的固一 IP 被中華電信鎖在 100M) 跟原 po 一樣接 tick/bidask 10 檔 (大台/小台 * 近月/次月 另加 大盤), callback 收到資料之後處理的程式碼不太漂亮, 處理資料結構/計算的過程中有拖到, 所以後面收到的資料就愈拖愈長. 修完程式之後平均每一筆資料進來的處理時間都小於 0.0001 秒. 或許可以測試一下, callback 收到資料直接吐 row data 到 log file 會不會發生一樣的問題.
> 
> 我的情況是偶發性的
> 有時候會發生 有時候不會

你怎麼處理訂閱資料的?

**Comment by ian15937** [comment]
def quote_callback(topic:str,quote:dict):
        temp=topic.split('/')
        isin=self.ID_to_ISIN[topic.split('/')[-1]]
        if temp[0]=='Q':
            msg={'T':quote['Time']}
            temp={}
            for i,p in enumerate(quote['AskPrice']):
                if quote['AskVolume'][i]>0:
                    temp[p]=quote['AskVolume'][i]
            if temp:
                msg['A']=temp
            temp={}
            for i,p in enumerate(quote['BidPrice']):
                if quote['BidVolume'][i]>0:
                    temp[p]=quote['BidVolume'][i]
            if temp:
                msg['B']=temp
            self.MQTTClient.publish('TAIFEX/'+isin+'/best5',dumps(msg),qos=2)        
        elif temp[0]=='L':
            msg=dict(
                T=quote['Time'],
                P=quote['Close'][0],
                S=0,
                V=quote['Volume'][0],
                D=quote['Date'].replace('/','-')
                )
            self.MQTTClient.publish('TAIFEX/'+isin+'/ticks',dumps(msg),qos=2)

**Comment by linsamtw** [comment]
> ```
> def quote_callback(topic:str,quote:dict):
>     temp=topic.split('/')
>     isin=self.ID_to_ISIN[topic.split('/')[-1]]
>     if temp[0]=='Q':
>         msg={'T':quote['Time']}
>         temp={}
>         for i,p in enumerate(quote['AskPrice']):
>             if quote['AskVolume'][i]>0:
>                 temp[p]=quote['AskVolume'][i]
>         if temp:
>             msg['A']=temp
>         temp={}
>         for i,p in enumerate(quote['BidPrice']):
>             if quote['BidVolume'][i]>0:
>                 temp[p]=quote['BidVolume'][i]
>         if temp:
>             msg['B']=temp
>         self.MQTTClient.publish('TAIFEX/'+isin+'/best5',dumps(msg),qos=2)        
>     elif temp[0]=='L':
>         msg=dict(
>             T=quote['Time'],
>             P=quote['Close'][0],
>             S=0,
>             V=quote['Volume'][0],
>             D=quote['Date'].replace('/','-')
>             )
>         self.MQTTClient.publish('TAIFEX/'+isin+'/ticks',dumps(msg),qos=2)
> ```

你也做太多處理了，一般來說，處理即時資料，都是先作暫存，例如存在 redis，
之後再去做資料清理，而不是直接收到馬上做資料清理

**Comment by ian15937** [comment]
> > ```
> > def quote_callback(topic:str,quote:dict):
> >     temp=topic.split('/')
> >     isin=self.ID_to_ISIN[topic.split('/')[-1]]
> >     if temp[0]=='Q':
> >         msg={'T':quote['Time']}
> >         temp={}
> >         for i,p in enumerate(quote['AskPrice']):
> >             if quote['AskVolume'][i]>0:
> >                 temp[p]=quote['AskVolume'][i]
> >         if temp:
> >             msg['A']=temp
> >         temp={}
> >         for i,p in enumerate(quote['BidPrice']):
> >             if quote['BidVolume'][i]>0:
> >                 temp[p]=quote['BidVolume'][i]
> >         if temp:
> >             msg['B']=temp
> >         self.MQTTClient.publish('TAIFEX/'+isin+'/best5',dumps(msg),qos=2)        
> >     elif temp[0]=='L':
> >         msg=dict(
> >             T=quote['Time'],
> >             P=quote['Close'][0],
> >             S=0,
> >             V=quote['Volume'][0],
> >             D=quote['Date'].replace('/','-')
> >             )
> >         self.MQTTClient.publish('TAIFEX/'+isin+'/ticks',dumps(msg),qos=2)
> > ```
> 
> 你也做太多處理了，一般來說，處理即時資料，都是先作暫存，例如存在 redis，
> 之後再去做資料清理，而不是直接收到馬上做資料清理

好我會試試看

**Comment by KN16H7** [comment]
看起來 code 不複雜啊, 我當時的測試方法很土炮 (因為當時慢到最誇張的是 lag 到火大直接把程式重開又好了):
- 收到的資料 raw data 存到 .log (最陽春的 open/write), 順便記錄資料發送時間 (L/Q 的 time), 收到資料的時間 (local time) - 如果兇手是網路, 這邊就可以結案
- 把 .log 逐筆吃回來丟回 topic string / dict, 根據 topic / dict 計算/寫檔/... / 記錄處理時間, 順便觀察記憶體使用量, 因為就算只是把 L data 一直 append 進 list 吃記憶體這種小白問題都可能會造成 callback 愈來愈慢, 但是也只有在造成 swap 到 disk 的狀況才會發生

**Comment by ian15937** [comment]
> 看起來 code 不複雜啊, 我當時的測試方法很土炮 (因為當時慢到最誇張的是 lag 到火大直接把程式重開又好了):
> 
> * 收到的資料 raw data 存到 .log (最陽春的 open/write), 順便記錄資料發送時間 (L/Q 的 time), 收到資料的時間 (local time) - 如果兇手是網路, 這邊就可以結案
> * 把 .log 逐筆吃回來丟回 topic string / dict, 根據 topic / dict 計算/寫檔/... / 記錄處理時間, 順便觀察記憶體使用量, 因為就算只是把 L data 一直 append 進 list 吃記憶體這種小白問題都可能會造成 callback 愈來愈慢, 但是也只有在造成 swap 到 disk 的狀況才會發生

我也覺得我那些處理應該1ms以內就結束了
不過我現在是丟到multiprocessing的Queue裡面讓另一個Process去處理
如果這幾天試都沒問題的話你可以參考看看

**Comment by linsamtw** [comment]
因為我們自己也有訂閱多檔報價做程式交易，比較沒有遇到這種情況

**Comment by SDpower** [comment]
把資料拋到不同thread後處理，不然像是台指期爆量卡住可不是幾秒的事。
