### ISSUE TITLE
匯入憑證問題

### ISSUE THREAD

**Issue by jeff9710109** [Sinotrade/Shioaji#99]
![image](https://user-images.githubusercontent.com/83211753/116334601-11fe1100-a808-11eb-9afb-153ee039f849.png)
# 匯入憑證
api.activate_ca(
    ca_path="/c/your/ca/path/Sinopac.pfx",
    ca_passwd="YOUR_CA_PASSWORD",
    person_id="Person of this Ca",
)
請問有甚麼建議呢

**Comment by ian15937** [comment]
ca_path寫你的憑證路徑
如果跟程式放在同一個資料夾裡就只要寫"Sinopac.pfx"就好

ca_passwd就是你的憑證密碼
如果你沒特別去改就是你的身分證字號(英文大寫)

person_id就是你的身分證字號(英文大寫)

**Comment by jeff9710109** [comment]
謝謝您
收穫良多，特別是"如果跟程式放在同一個資料夾裡就只要寫"Sinopac.pfx"就好"

ian15937 ***@***.***> 於 2021年5月6日 週四 上午10:47寫道：

**Comment by ypochien** [comment]
感謝回覆

**Comment by jeff9710109** [comment]
![image](https://user-images.githubusercontent.com/83211753/124763520-a1d9dd00-df66-11eb-839f-ae15939bbcec.png)
頗有趣~~之前可以匯入，現在又不行，ca_path寫你的憑證路徑
ca_passwd就是你的憑證密碼
如果你沒特別去改就是你的身分證字號(英文大寫)
person_id就是你的身分證字號(英文大寫)
這三個都是輸入正確，想請教各位前輩是什麼原因呢?
